'use client';

import { useState } from 'react';
import DashboardLayout from '@/components/DashboardLayout';
import StructuredOutput from '@/components/ai/StructuredOutput';
import { aiAPI } from '@/lib/api';

type WidgetKey = 'gap' | 'forecast' | 'audit' | 'risk';

interface WidgetState {
  loading: boolean;
  result: string | null;
  error: string | null;
}

const initialState: WidgetState = { loading: false, result: null, error: null };

interface WidgetSpec {
  key: WidgetKey;
  title: string;
  description: string;
  feature: string;
  run: () => Promise<{ data: { data?: { result?: string } } }>;
}

const WIDGETS: WidgetSpec[] = [
  {
    key: 'gap',
    title: 'Compliance Gap Analysis',
    description: 'Identifies the most material gaps across your active frameworks and ranks them by impact.',
    feature: 'gap_analysis',
    run: () => aiAPI.gapAnalysis(),
  },
  {
    key: 'forecast',
    title: 'Compliance Forecast',
    description: 'Projects implementation trajectory based on the current pace of control completion.',
    feature: 'compliance_forecast',
    run: () => aiAPI.complianceForecast(),
  },
  {
    key: 'audit',
    title: 'Audit Readiness',
    description: 'Highlights what is ready, what is at risk, and what needs immediate attention before fieldwork.',
    feature: 'audit_readiness',
    run: () => aiAPI.auditReadiness(),
  },
  {
    key: 'risk',
    title: 'Risk Heatmap',
    description: 'Surfaces the top control-level risks weighted by criticality and current implementation state.',
    feature: 'risk_heatmap',
    run: () => aiAPI.riskHeatmap(),
  },
];

export default function AIInsightsPage() {
  const [states, setStates] = useState<Record<WidgetKey, WidgetState>>({
    gap: { ...initialState },
    forecast: { ...initialState },
    audit: { ...initialState },
    risk: { ...initialState },
  });

  const runWidget = async (widget: WidgetSpec) => {
    setStates(prev => ({ ...prev, [widget.key]: { loading: true, result: null, error: null } }));
    try {
      const res = await widget.run();
      const result = res.data?.data?.result ?? '';
      setStates(prev => ({ ...prev, [widget.key]: { loading: false, result, error: null } }));
    } catch (err) {
      const error = err instanceof Error ? err.message : 'Request failed';
      const responseError = (err as { response?: { data?: { error?: string } } })?.response?.data?.error;
      setStates(prev => ({
        ...prev,
        [widget.key]: { loading: false, result: null, error: responseError ?? error },
      }));
    }
  };

  return (
    <DashboardLayout>
      <div className="max-w-5xl mx-auto">
        <header className="mb-6">
          <h1 className="text-2xl font-bold text-gray-900">AI Insights</h1>
          <p className="mt-1 text-sm text-gray-600">
            Optional AI-assisted analysis to speed up gap analysis, forecasting, and audit prep. AI is a
            supplement to your compliance work, not a replacement for it.
          </p>
          <div className="mt-3 rounded-md bg-amber-50 border border-amber-200 px-3 py-2 text-xs text-amber-800">
            Generated by AI — review every output before relying on it. Outputs may be incomplete or
            occasionally inaccurate.
          </div>
        </header>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          {WIDGETS.map(widget => {
            const state = states[widget.key];
            return (
              <section
                key={widget.key}
                className="bg-white rounded-lg border border-gray-200 shadow-sm p-5 flex flex-col"
              >
                <div className="flex items-start justify-between gap-3">
                  <div>
                    <h2 className="text-base font-semibold text-gray-900">{widget.title}</h2>
                    <p className="mt-1 text-xs text-gray-600">{widget.description}</p>
                  </div>
                  <button
                    type="button"
                    onClick={() => runWidget(widget)}
                    disabled={state.loading}
                    className="shrink-0 px-3 py-1.5 text-xs font-medium rounded-md bg-purple-600 text-white hover:bg-purple-700 disabled:opacity-50 disabled:cursor-not-allowed"
                  >
                    {state.loading ? 'Generating…' : state.result ? 'Refresh' : 'Generate'}
                  </button>
                </div>

                <div className="mt-4 flex-1 min-h-[120px]">
                  {state.loading && (
                    <div className="text-xs text-gray-500">Running analysis…</div>
                  )}
                  {state.error && (
                    <div className="rounded-md border border-red-200 bg-red-50 px-3 py-2 text-xs text-red-700">
                      {state.error}
                    </div>
                  )}
                  {state.result && !state.loading && !state.error && (
                    <StructuredOutput
                      content={state.result}
                      feature={widget.feature}
                      showActions={false}
                    />
                  )}
                  {!state.result && !state.loading && !state.error && (
                    <p className="text-xs text-gray-400">
                      Click Generate to run this analysis on your current organization data.
                    </p>
                  )}
                </div>
              </section>
            );
          })}
        </div>
      </div>
    </DashboardLayout>
  );
}
