module.exports = {
    code: 'international_ai_governance', name: 'International AI Governance Laws', version: '2025',
    category: 'AI Governance', tier_required: 'govcloud',
    description: 'Comprehensive coverage of enacted international AI governance laws across 10+ jurisdictions: EU AI Act (Regulation 2024/1689), UK AI Regulation Approach, Canada AIDA (Bill C-27), Brazil LGPD AI Provisions, Singapore PDPA + AI Governance Framework 2.0, Japan APPI + AI Strategy, South Korea AI Basic Act, China Generative AI Regulation + Algorithm Recommendation Regulation, Australia Privacy Act AI Ethics Framework, and India DPDP Act 2023. Controls are crosswalked to NIST AI RMF and EU AI Act so evidence satisfies multiple jurisdictions.',
    controls: [
      // European Union — AI Act (Regulation 2024/1689) enhanced
      { control_id: 'EU-AIA-1', title: 'EU AI Act — Prohibited AI Practices (Art. 5)', description: 'Prohibit AI practices that pose unacceptable risk: subliminal manipulation, exploitation of vulnerabilities, social scoring by public authorities, real-time biometric surveillance in public spaces, and emotion recognition in workplace/education. Implement a prohibited-use checklist reviewed quarterly. (Regulation 2024/1689, Art. 5)', priority: '1', control_type: 'policy' },
      { control_id: 'EU-AIA-2', title: 'EU AI Act — High-Risk AI Classification (Art. 6 & Annex III)', description: 'Classify AI systems as high-risk if they fall within Annex III categories (biometrics, critical infrastructure, education, employment, essential services, law enforcement, migration, justice). Maintain a classification register reviewed on material changes. (Art. 6)', priority: '1', control_type: 'strategic' },
      { control_id: 'EU-AIA-3', title: 'EU AI Act — Risk Management System Lifecycle (Art. 9)', description: 'Implement a continuous risk management system covering identification and analysis of known and foreseeable risks, estimation and evaluation when used as intended and under misuse, and risk mitigation measures. Document and update throughout the AI lifecycle. (Art. 9)', priority: '1', control_type: 'strategic' },
      { control_id: 'EU-AIA-4', title: 'EU AI Act — Data Governance for High-Risk AI (Art. 10)', description: 'Ensure training, validation, and testing datasets satisfy quality criteria: relevance, representativeness, freedom from errors, completeness, and appropriate statistical properties. Implement data governance addressing potential biases. Document dataset provenance and preprocessing. (Art. 10)', priority: '1', control_type: 'technical' },
      { control_id: 'EU-AIA-5', title: 'EU AI Act — Technical Documentation (Art. 11 & Annex IV)', description: 'Prepare comprehensive technical documentation (Annex IV) before placing a high-risk AI system on the EU market: system description, architecture, design specifications, training methodologies, validation results, performance metrics, and intended purpose. (Art. 11)', priority: '1', control_type: 'organizational' },
      { control_id: 'EU-AIA-6', title: 'EU AI Act — Automatic Event Logging (Art. 12)', description: 'Design high-risk AI systems to automatically generate audit logs: system activation/deactivation, input data, output decisions, human oversight interventions, and reference database queries. Retain logs for at least 6 months. (Art. 12)', priority: '1', control_type: 'technical' },
      { control_id: 'EU-AIA-7', title: 'EU AI Act — Transparency and Instructions for Use (Art. 13)', description: 'Ensure high-risk AI systems are sufficiently transparent. Provide instructions for use including: provider identity, system capabilities and limitations, performance metrics, human oversight measures, expected lifetime, and maintenance requirements. (Art. 13)', priority: '1', control_type: 'organizational' },
      { control_id: 'EU-AIA-8', title: 'EU AI Act — Human Oversight Measures (Art. 14)', description: 'Design high-risk AI systems to enable effective human oversight: ability to understand capabilities and limitations, ability to disregard or override AI outputs, ability to interrupt operation, and assignment of oversight responsibility to competent natural persons. (Art. 14)', priority: '1', control_type: 'organizational' },
      { control_id: 'EU-AIA-9', title: 'EU AI Act — GPAI Model Transparency and Systemic Risk (Art. 53 & 55)', description: 'For GPAI models: provide technical documentation, publish training data summary, implement copyright compliance, and establish incident reporting. For GPAI with systemic risk (>10^25 FLOPs): conduct adversarial testing, notify incidents to the AI Office, implement cybersecurity measures. (Art. 53, 55)', priority: '1', control_type: 'strategic' },
      { control_id: 'EU-AIA-10', title: 'EU AI Act — Fundamental Rights Impact Assessment (Art. 27)', description: 'Before deploying high-risk AI in sectors affecting fundamental rights, conduct an impact assessment covering: purpose, system description, deployment geography, affected persons, specific risks identified, and proportionality. Register in the EU database. (Art. 27)', priority: '1', control_type: 'strategic' },
      // United Kingdom — Pro-Innovation AI Regulatory Approach
      { control_id: 'UK-AI-1', title: 'UK AI — Cross-Sector Safety Requirements', description: 'Apply the UK AI safety principle: AI systems must be technically secure and function as designed. Implement a safety case covering failure modes, adversarial robustness, and incident response applicable to your sector regulator (FCA, CMA, ICO, Ofcom). (DSIT AI Framework, Safety Principle)', priority: '1', control_type: 'strategic' },
      { control_id: 'UK-AI-2', title: 'UK AI — Transparency and Explainability', description: 'Apply the UK transparency principle: be transparent about when AI is used, the basis for AI-influenced decisions, and provide meaningful explanations. Comply with ICO guidance on AI and data protection transparency under UK GDPR. (DSIT AI Framework, Transparency Principle)', priority: '1', control_type: 'policy' },
      { control_id: 'UK-AI-3', title: 'UK AI — Fairness and Non-Discrimination', description: 'Apply the UK fairness principle: AI systems must not undermine equality law. Conduct bias assessments covering the nine protected characteristics under the UK Equality Act 2010 for AI influencing decisions about individuals. Document and remediate disparate impacts. (DSIT AI Framework, Fairness Principle)', priority: '1', control_type: 'strategic' },
      { control_id: 'UK-AI-4', title: 'UK AI — Accountability and Governance', description: 'Apply the UK accountability principle: establish AI governance structures with defined roles, responsibilities, and escalation paths. Maintain an AI register, conduct regular reviews, and designate senior accountability for AI risk. Comply with FCA/PRA model risk management where applicable. (DSIT AI Framework)', priority: '1', control_type: 'organizational' },
      { control_id: 'UK-AI-5', title: 'UK AI — Contestability and Redress', description: 'Apply the UK contestability principle: where AI influences significant decisions about individuals, provide clear routes to contest decisions and seek human review. Implement an AI complaints and appeals process with defined SLAs. (DSIT AI Framework, Contestability Principle)', priority: '2', control_type: 'policy' },
      // Canada — AIDA (Artificial Intelligence and Data Act, Bill C-27)
      { control_id: 'CA-AIDA-1', title: 'Canada AIDA — High-Impact AI System Identification', description: 'Identify AI systems meeting the definition of "high-impact system" under AIDA: systems making automated decisions having significant effects in employment, access to services, criminal justice, or health. Maintain an inventory of all high-impact systems. (AIDA Bill C-27, Part 3, s. 5)', priority: '1', control_type: 'organizational' },
      { control_id: 'CA-AIDA-2', title: 'Canada AIDA — Risk Assessment and Mitigation', description: 'Conduct risk assessments for high-impact AI systems prior to deployment and at defined intervals covering risks to individuals, society, and democratic institutions. Document implemented mitigation measures proportionate to identified risks. (AIDA Bill C-27, s. 6-7)', priority: '1', control_type: 'strategic' },
      { control_id: 'CA-AIDA-3', title: 'Canada AIDA — Transparency and Plain-Language Disclosure', description: 'Make publicly available plain-language descriptions of high-impact AI systems in use, their general purposes, decision types, and available recourse mechanisms. Publish on the organizational website and update on material changes. (AIDA Bill C-27, s. 10)', priority: '1', control_type: 'policy' },
      { control_id: 'CA-AIDA-4', title: 'Canada AIDA — Monitoring and Record-Keeping', description: 'Monitor deployed high-impact AI systems for performance and unintended consequences. Maintain records of training data descriptions, risk assessment results, mitigation measures, and monitoring outcomes for a minimum of 10 years after system retirement. (AIDA Bill C-27, s. 12)', priority: '2', control_type: 'organizational' },
      // Brazil — LGPD AI Provisions & AI Bill (PL 2338/2023)
      { control_id: 'BR-AI-1', title: 'Brazil — Automated Processing Transparency (LGPD Art. 20)', description: 'When personal data is processed by automated means for decisions affecting an individual, provide upon request: information about the criteria and procedures used, right to request human review, and a plain-language explanation of the decision. (Lei 13.709/2018, Art. 20)', priority: '1', control_type: 'policy' },
      { control_id: 'BR-AI-2', title: 'Brazil — Right to Human Review of Automated Decisions (LGPD Art. 20)', description: 'Establish a documented process allowing data subjects to request human review of decisions based solely on automated processing of personal data that affect their interests. Process requests within 15 days and document outcomes. (Lei 13.709/2018, Art. 20, §3)', priority: '1', control_type: 'policy' },
      { control_id: 'BR-AI-3', title: 'Brazil AI Bill — High-Risk AI Impact Assessment (PL 2338/2023)', description: 'For high-risk AI systems under the Brazil AI Bill (critical infrastructure, employment, biometrics, criminal justice): conduct and document an algorithmic impact assessment covering purpose, methodology, data used, potential harms, and mitigation measures before deployment. (PL 2338/2023, Art. 15)', priority: '1', control_type: 'strategic' },
      { control_id: 'BR-AI-4', title: 'Brazil AI Bill — Non-Discrimination and Bias Controls', description: 'Implement technical and organizational measures to prevent AI systems from producing discriminatory outputs based on race, color, ethnicity, religion, national origin, gender, sexual orientation, or disability. Conduct periodic bias audits and document remediation actions. (PL 2338/2023, Art. 6)', priority: '1', control_type: 'technical' },
      // Singapore — PDPA + AI Governance Framework 2.0
      { control_id: 'SG-AI-1', title: 'Singapore — Internal AI Governance Structure (AIGF 2.0)', description: 'Establish an internal AI governance structure with senior leadership accountability, defined AI ethics principles, clear policies on permitted AI uses, and designated responsibilities for AI risk management. Align with the PDPC Model AI Governance Framework 2.0 and IMDA guidelines. (AIGF 2.0, Part 2)', priority: '1', control_type: 'organizational' },
      { control_id: 'SG-AI-2', title: 'Singapore — Human Involvement in AI Decision-Making (AIGF 2.0)', description: 'Determine the appropriate degree of human oversight for each AI use case based on probability of harm and severity of impact. For high-risk decisions (financial, medical, legal), require mandatory human review. Document the human oversight model in AI governance policies. (AIGF 2.0, Part 3)', priority: '1', control_type: 'organizational' },
      { control_id: 'SG-AI-3', title: 'Singapore — AI Operations Management and Model Monitoring', description: 'Implement operational controls covering: AI model documentation, pre-deployment validation, ongoing performance monitoring, data quality management, and version control. Establish minimum performance thresholds and trigger-based review procedures for model degradation. (AIGF 2.0, Part 4)', priority: '1', control_type: 'technical' },
      { control_id: 'SG-AI-4', title: 'Singapore — PDPA AI Data Protection Obligations', description: 'Comply with PDPA obligations for AI systems processing personal data: obtain valid consent or establish a valid legal basis, apply purpose limitation, implement data minimization in training datasets, and notify affected individuals when AI decisions materially affect them. (PDPA 2012, as amended 2020)', priority: '1', control_type: 'technical' },
      // Japan — APPI + AI Strategy 2022
      { control_id: 'JP-AI-1', title: 'Japan — APPI AI Data Processing Governance', description: 'Comply with the Act on the Protection of Personal Information (APPI) for AI systems: establish a legitimate purpose of use, notify individuals of purpose, implement security management measures proportionate to risk, and obtain consent for sensitive personal information used in AI training. (APPI Art. 18, 20, 24)', priority: '1', control_type: 'technical' },
      { control_id: 'JP-AI-2', title: 'Japan — AI Development and Utilization Principles (MIC/METI)', description: 'Apply the 10 AI development principles from Japan MIC/METI guidelines: human-centricity, education/literacy, privacy protection, security, fair competition, fairness, transparency, innovation, accountability, and safety. Document how each principle is operationalized in AI system design and deployment policies.', priority: '1', control_type: 'policy' },
      { control_id: 'JP-AI-3', title: 'Japan — Generative AI Guidelines (Cabinet AI Strategy 2024)', description: 'For generative AI operating in Japan: implement copyright compliance measures, establish content provenance mechanisms, publish usage guidelines for employees, and disclose to users when AI-generated content is being provided. Align with Cabinet Office Integrated Innovation Strategy guidelines on generative AI.', priority: '2', control_type: 'policy' },
      // South Korea — AI Basic Act (Act No. 20469)
      { control_id: 'KR-AI-1', title: 'South Korea AI Basic Act — High-Impact AI Risk Assessment', description: 'For AI classified as high-impact under the AI Basic Act (healthcare, employment, credit, education, law enforcement, critical infrastructure): conduct a pre-deployment impact assessment covering risks, data sources, mitigation measures, and monitoring plan. Submit to the Korea Communications Commission or applicable regulator as required. (AI Basic Act, Art. 27)', priority: '1', control_type: 'strategic' },
      { control_id: 'KR-AI-2', title: 'South Korea AI Basic Act — Transparency and Disclosure', description: 'Disclose to users: that they are interacting with an AI system, the purpose and key characteristics of the AI, available avenues for recourse, and the provider identity. For AI-generated content, implement technical disclosure measures. (AI Basic Act, Art. 28)', priority: '1', control_type: 'policy' },
      { control_id: 'KR-AI-3', title: 'South Korea AI Basic Act — Governance and Accountability', description: 'Establish an AI governance framework aligned with the AI Basic Act: appoint an AI safety officer for high-impact systems, implement an internal AI ethics committee or oversight body, and establish an incident response procedure for AI-related harms. (AI Basic Act, Art. 31)', priority: '2', control_type: 'organizational' },
      // China — Generative AI Regulation + Algorithm Recommendation Regulation
      { control_id: 'CN-AI-1', title: 'China — Generative AI Service Disclosure Requirements (CAC 2023)', description: 'Generative AI services in China must: obtain user consent before content generation, label AI-generated content with visible and covert watermarks, implement content security review mechanisms, and maintain logs of user instructions and AI outputs for 6 months. (CAC Measures for Generative AI, Art. 12, 17)', priority: '1', control_type: 'technical' },
      { control_id: 'CN-AI-2', title: 'China — Algorithm Recommendation Transparency and User Control (CAC 2022)', description: 'Algorithm recommendation services must: disclose use of algorithmic recommendations, provide users the ability to disable personalized recommendations, prohibit price discrimination based on user characteristics, and file algorithm records with the CAC for significant platforms. (Algorithm Recommendation Measures, Art. 9, 17, 21)', priority: '1', control_type: 'policy' },
      { control_id: 'CN-AI-3', title: 'China — AI Content Security and Prohibited Uses', description: 'Ensure AI systems do not generate content that endangers national security, disrupts social order, violates social ethics, or spreads false information. Implement content moderation aligned with CAC internet information security requirements. Conduct quarterly compliance reviews. (CAC Generative AI Measures, Art. 4, 15)', priority: '1', control_type: 'policy' },
      { control_id: 'CN-AI-4', title: 'China — Deep Synthesis (Deepfake) Regulation Compliance (CAC 2022)', description: 'Comply with the Deep Synthesis Regulation: label all AI-generated synthetic audio, video, and images with conspicuous technical markers; obtain consent before creating deepfake content of identifiable individuals; provide real-name registration for users of deep synthesis services in China. (Deep Synthesis Provisions, Art. 14, 16)', priority: '1', control_type: 'technical' },
      // Australia — Privacy Act + AI Ethics Framework
      { control_id: 'AU-AI-1', title: 'Australia — Privacy Act AI Transparency (APPs)', description: 'When AI systems make or significantly influence decisions about Australian individuals, comply with Australian Privacy Principles: disclose automated decision-making in collection notices, implement the open and transparent management principle (APP 1), and provide individuals with access to personal information used in AI decisions. (Privacy Act 1988, APPs 1, 5, 12)', priority: '1', control_type: 'policy' },
      { control_id: 'AU-AI-2', title: 'Australia — National AI Ethics Framework Alignment (DISR 2019)', description: 'Apply the Australian AI Ethics Framework principles: human, societal and environmental wellbeing; human-centred values; fairness; privacy protection and security; reliability and safety; transparency and explainability; contestability; and accountability. Document principle compliance in AI governance policies.', priority: '1', control_type: 'policy' },
      { control_id: 'AU-AI-3', title: 'Australia — Automated Decision Governance', description: 'Implement governance controls for automated decisions affecting individuals: maintain an automated decision system record, conduct human rights and privacy impact assessments, implement human review mechanisms for consequential decisions, and publish an automated decision register consistent with APS guidance. (APS Automated Decision-Making Better Practice Guide)', priority: '2', control_type: 'organizational' },
      // India — Digital Personal Data Protection Act 2023
      { control_id: 'IN-AI-1', title: 'India DPDP Act — Lawful Basis and Consent for AI Data Processing', description: 'For AI systems processing personal digital data of Indian residents: establish a valid consent or legitimate use basis, ensure consent is free, specific, informed, and unconditional, maintain consent artefacts, and provide a mechanism for data principals to withdraw consent affecting AI processing within a reasonable timeframe. (DPDP Act 2023, Sections 6, 7)', priority: '1', control_type: 'technical' },
      { control_id: 'IN-AI-2', title: 'India DPDP Act — Data Principal Rights in AI Contexts', description: 'Implement processes to fulfil data principal rights for AI-processed data: right to access a summary of personal data and processing activities, right to correction and erasure of inaccurate data used in AI models, right to grievance redressal within 30 days, and right to nominate. (DPDP Act 2023, Sections 11-14)', priority: '1', control_type: 'policy' },
      { control_id: 'IN-AI-3', title: 'India DPDP Act — Data Localisation and Transfer Compliance', description: 'Comply with data localisation requirements for AI training and inference: do not transfer personal data of Indian residents to restricted countries or territories. Implement technical controls to enforce data residency for AI workloads and maintain transfer documentation. (DPDP Act 2023, Section 16)', priority: '2', control_type: 'technical' },
      // Cross-cutting multi-jurisdiction controls
      { control_id: 'INTL-CORE-1', title: 'Multi-Jurisdiction AI Compliance Program', description: 'Establish a centralized international AI compliance program tracking applicable laws by jurisdiction, with a compliance calendar for key deadlines (EU AI Act phases: 2025-2027), regulatory watch process covering 50+ countries, policy update procedure, and designated compliance owners per active jurisdiction.', priority: '1', control_type: 'strategic' },
      { control_id: 'INTL-CORE-2', title: 'Unified International AI System Register', description: 'Maintain a unified register of all AI systems in use internationally, documenting: countries of deployment, applicable national laws, risk tier per jurisdiction, impact assessment status, audit dates, and assigned compliance owners. Update on deployment of new systems or expansion into new markets.', priority: '1', control_type: 'organizational' },
      { control_id: 'INTL-CORE-3', title: 'Cross-Jurisdiction Algorithmic Fairness Baseline', description: 'Implement baseline fairness controls satisfying anti-discrimination requirements across EU AI Act, UK Equality Act, Canada AIDA, Brazil AI Bill, and South Korea AI Basic Act simultaneously: protected-characteristic bias testing, impact ratio analysis, disparity documentation, and corrective action procedures.', priority: '1', control_type: 'technical' },
      { control_id: 'INTL-CORE-4', title: 'International AI Content Provenance and Watermarking', description: 'Implement AI content provenance and watermarking mechanisms satisfying EU AI Act (Art. 50), China CAC deep synthesis rules, and emerging international standards (C2PA, ISO/IEC 42101). Apply visible and non-visible markers to AI-generated text, images, audio, and video across all markets.', priority: '1', control_type: 'technical' }, // ip-hygiene:ignore
      { control_id: 'INTL-CORE-5', title: 'Global AI Incident Reporting and Response', description: 'Establish a global AI incident reporting and response program: unified incident classification (safety, bias, privacy, security), jurisdiction-specific reporting timelines (EU: immediately for serious incidents; UK: sector-regulator timelines; China: CAC 24-hour window for significant incidents), and a cross-border root-cause analysis process.', priority: '1', control_type: 'organizational' },
      { control_id: 'INTL-CORE-6', title: 'International AI Regulatory Change Management', description: 'Monitor AI legislative and regulatory developments across 50+ countries using a quarterly regulatory scan. Update internal policies and controls within 90 days of enacted laws. Maintain a jurisdiction-law tracking log covering EU, UK, Canada, Brazil, Singapore, Japan, South Korea, China, Australia, India, and emerging markets.', priority: '2', control_type: 'strategic' },
    ]
  };
