module.exports = {
    code: 'iso_27001', name: 'ISO/IEC 27001:2022', version: '2022',
    category: 'Information Security', tier_required: 'community',
    framework_group: 'iso_27000',
    description: 'Information security management system (ISMS) standard with Annex A controls.',
    controls: [
      { control_id: 'A.5.1', title: 'Policies for Information Security', description: 'A set of policies for information security shall be defined, approved by management, and communicated.', priority: '1', control_type: 'policy' },
      { control_id: 'A.5.2', title: 'Information Security Roles', description: 'Information security roles and responsibilities shall be defined and allocated.', priority: '1', control_type: 'organizational' },
      { control_id: 'A.5.3', title: 'Segregation of Duties', description: 'Conflicting duties and areas of responsibility shall be segregated to reduce unauthorized modification.', priority: '2', control_type: 'organizational' },
      { control_id: 'A.5.4', title: 'Management Responsibilities', description: 'Management shall require all personnel to apply information security in accordance with the policy.', priority: '1', control_type: 'organizational' },
      { control_id: 'A.5.7', title: 'Threat Intelligence', description: 'Information relating to information security threats shall be collected and analyzed.', priority: '2', control_type: 'technical' },
      { control_id: 'A.5.8', title: 'Information Security in Project Management', description: 'Information security shall be integrated into project management regardless of the project type.', priority: '2', control_type: 'organizational' },
      { control_id: 'A.5.9', title: 'Inventory of Information and Assets', description: 'An inventory of information and other associated assets shall be developed and maintained.', priority: '1', control_type: 'technical' },
      { control_id: 'A.5.10', title: 'Acceptable Use of Information', description: 'Rules for the acceptable use of information and assets shall be identified and documented.', priority: '2', control_type: 'policy' },
      { control_id: 'A.5.15', title: 'Access Control', description: 'Rules to control physical and logical access to information shall be established and implemented.', priority: '1', control_type: 'technical' },
      { control_id: 'A.5.16', title: 'Identity Management', description: 'The full lifecycle of identities shall be managed.', priority: '1', control_type: 'technical' },
      { control_id: 'A.5.17', title: 'Authentication Information', description: 'Allocation and management of authentication information shall be controlled.', priority: '1', control_type: 'technical' },
      { control_id: 'A.5.18', title: 'Access Rights', description: 'Access rights to information and assets shall be provisioned, reviewed, and removed.', priority: '1', control_type: 'technical' },
      { control_id: 'A.5.23', title: 'Information Security for Cloud Services', description: 'Processes for acquisition, use, management, and exit from cloud services shall be established.', priority: '1', control_type: 'technical' },
      { control_id: 'A.5.24', title: 'Information Security Incident Management', description: 'Information security incident management shall be planned and prepared.', priority: '1', control_type: 'organizational' },
      { control_id: 'A.5.25', title: 'Assessment and Decision on Events', description: 'Information security events shall be assessed and decided whether to categorize as incidents.', priority: '2', control_type: 'organizational' },
      { control_id: 'A.5.26', title: 'Response to Information Security Incidents', description: 'Information security incidents shall be responded to in accordance with documented procedures.', priority: '1', control_type: 'organizational' },
      { control_id: 'A.5.29', title: 'Information Security During Disruption', description: 'Information security continuity shall be embedded in business continuity management systems.', priority: '1', control_type: 'organizational' },
      { control_id: 'A.5.30', title: 'ICT Readiness for Business Continuity', description: 'ICT readiness shall be planned, implemented, and tested based on business continuity objectives.', priority: '1', control_type: 'technical' },
      { control_id: 'A.5.36', title: 'Compliance with Policies and Standards', description: 'Compliance with the information security policy and standards shall be regularly reviewed.', priority: '2', control_type: 'organizational' },
      { control_id: 'A.6.1', title: 'Screening', description: 'Background verification checks on all candidates shall be carried out prior to joining.', priority: '3', control_type: 'organizational' },
      { control_id: 'A.6.3', title: 'Information Security Awareness', description: 'Personnel shall receive appropriate security awareness education and training.', priority: '2', control_type: 'organizational' },
      { control_id: 'A.7.1', title: 'Physical Security Perimeters', description: 'Security perimeters shall be defined and used to protect areas containing information.', priority: '2', control_type: 'physical' },
      { control_id: 'A.7.4', title: 'Physical Security Monitoring', description: 'Premises shall be continuously monitored for unauthorized physical access.', priority: '2', control_type: 'physical' },
      { control_id: 'A.8.1', title: 'User Endpoint Devices', description: 'Information stored on, processed by, or accessible via user endpoint devices shall be protected.', priority: '1', control_type: 'technical' },
      { control_id: 'A.8.2', title: 'Privileged Access Rights', description: 'The allocation and use of privileged access rights shall be restricted and managed.', priority: '1', control_type: 'technical' },
      { control_id: 'A.8.3', title: 'Information Access Restriction', description: 'Access to information and system functions shall be restricted in accordance with access control policy.', priority: '1', control_type: 'technical' },
      { control_id: 'A.8.5', title: 'Secure Authentication', description: 'Secure authentication technologies and procedures shall be established based on access restrictions.', priority: '1', control_type: 'technical' },
      { control_id: 'A.8.7', title: 'Protection Against Malware', description: 'Protection against malware shall be implemented and supported by user awareness.', priority: '1', control_type: 'technical' },
      { control_id: 'A.8.8', title: 'Management of Technical Vulnerabilities', description: 'Information about technical vulnerabilities shall be obtained and exposure evaluated.', priority: '1', control_type: 'technical' },
      { control_id: 'A.8.9', title: 'Configuration Management', description: 'Configurations including security configurations shall be established, documented, and maintained.', priority: '1', control_type: 'technical' },
      { control_id: 'A.8.10', title: 'Information Deletion', description: 'Information stored in information systems or devices shall be deleted when no longer required.', priority: '2', control_type: 'technical' },
      { control_id: 'A.8.12', title: 'Data Leakage Prevention', description: 'Data leakage prevention measures shall be applied to systems and networks containing sensitive data.', priority: '1', control_type: 'technical' },
      { control_id: 'A.8.13', title: 'Information Backup', description: 'Backup copies of information, software, and systems shall be maintained and regularly tested.', priority: '1', control_type: 'technical' },
      { control_id: 'A.8.15', title: 'Logging', description: 'Logs that record activities, exceptions, faults, and other relevant events shall be produced and stored.', priority: '1', control_type: 'technical' },
      { control_id: 'A.8.16', title: 'Monitoring Activities', description: 'Networks, systems, and applications shall be monitored for anomalous behavior.', priority: '1', control_type: 'technical' },
      { control_id: 'A.8.20', title: 'Networks Security', description: 'Networks and network devices shall be secured, managed, and controlled.', priority: '1', control_type: 'technical' },
      { control_id: 'A.8.24', title: 'Use of Cryptography', description: 'Rules for the effective use of cryptography shall be defined and implemented.', priority: '1', control_type: 'technical' },
      { control_id: 'A.8.25', title: 'Secure Development Lifecycle', description: 'Rules for the secure development of software and systems shall be established and applied.', priority: '2', control_type: 'technical' },
      { control_id: 'A.8.28', title: 'Secure Coding', description: 'Secure coding principles shall be applied to software development.', priority: '2', control_type: 'technical' },
    ]
  };
