module.exports = {
    code: 'nist_csf_2.0', name: 'NIST Cybersecurity Framework 2.0', version: '2.0',
    category: 'Cybersecurity', tier_required: 'community',
    description: 'Comprehensive cybersecurity risk management framework with 6 core functions aligned to system lifecycle (NIST 800-160).',
    controls: [
      // GOVERN
      { control_id: 'GV.OC-01', title: 'Organizational Context - Mission Understanding', description: 'The organizational mission is understood and informs cybersecurity risk management.', priority: '1', control_type: 'strategic' },
      { control_id: 'GV.OC-02', title: 'Organizational Context - Internal Stakeholders', description: 'Internal stakeholders understand and support the cybersecurity risk management strategy.', priority: '2', control_type: 'strategic' },
      { control_id: 'GV.OC-03', title: 'Organizational Context - Legal Requirements', description: 'Legal, regulatory, and contractual requirements regarding cybersecurity are understood and managed.', priority: '1', control_type: 'strategic' },
      { control_id: 'GV.OC-04', title: 'Organizational Context - Critical Objectives', description: 'Critical objectives, capabilities, and services that stakeholders depend on are determined.', priority: '1', control_type: 'strategic' },
      { control_id: 'GV.OC-05', title: 'Organizational Context - Dependencies Understood', description: 'Outcomes, capabilities, and services that the organization depends on are understood and communicated.', priority: '2', control_type: 'strategic' },
      { control_id: 'GV.RM-01', title: 'Risk Management - Strategy Established', description: 'Risk management objectives are established and expressed as a strategy accepted by stakeholders.', priority: '1', control_type: 'strategic' },
      { control_id: 'GV.RM-02', title: 'Risk Management - Risk Appetite Statement', description: 'Risk appetite and tolerance statements are established, communicated, and maintained.', priority: '1', control_type: 'strategic' },
      { control_id: 'GV.RM-03', title: 'Risk Management - Supply Chain Risk', description: 'Cybersecurity supply chain risk management activities are integrated into risk management processes.', priority: '2', control_type: 'strategic' },
      { control_id: 'GV.RR-01', title: 'Roles & Responsibilities - Leadership Accountability', description: 'Organizational leadership is accountable for cybersecurity risk and fosters a risk-aware culture.', priority: '1', control_type: 'organizational' },
      { control_id: 'GV.RR-02', title: 'Roles & Responsibilities - Authority Defined', description: 'Roles, responsibilities, and authorities for cybersecurity risk management are established and communicated.', priority: '2', control_type: 'organizational' },
      { control_id: 'GV.PO-01', title: 'Policy - Cybersecurity Policy Established', description: 'A cybersecurity risk management policy based on organizational context is established and communicated.', priority: '1', control_type: 'policy' },
      { control_id: 'GV.PO-02', title: 'Policy - Policy Review and Update', description: 'The cybersecurity risk management policy is reviewed, updated, and communicated based on changes.', priority: '2', control_type: 'policy' },
      { control_id: 'GV.SC-01', title: 'Supply Chain - Cyber Supply Chain Risk Mgmt', description: 'A cyber supply chain risk management program is established including processes to identify and manage risks.', priority: '2', control_type: 'strategic' },
      // IDENTIFY
      { control_id: 'ID.AM-01', title: 'Asset Management - Hardware Inventory', description: 'Inventories of hardware managed by the organization are maintained.', priority: '1', control_type: 'technical' },
      { control_id: 'ID.AM-02', title: 'Asset Management - Software Inventory', description: 'Inventories of software, services, and systems managed by the organization are maintained.', priority: '1', control_type: 'technical' },
      { control_id: 'ID.AM-03', title: 'Asset Management - Data Flow Mapping', description: 'Representations of authorized network communication and data flows are maintained.', priority: '2', control_type: 'technical' },
      { control_id: 'ID.AM-04', title: 'Asset Management - External Systems Cataloged', description: 'Inventories of services provided by suppliers are maintained.', priority: '2', control_type: 'technical' },
      { control_id: 'ID.AM-05', title: 'Asset Management - Asset Prioritization', description: 'Assets are prioritized based on classification, criticality, and business value.', priority: '1', control_type: 'strategic' },
      { control_id: 'ID.RA-01', title: 'Risk Assessment - Vulnerability Identification', description: 'Vulnerabilities in assets are identified, validated, and recorded.', priority: '1', control_type: 'technical' },
      { control_id: 'ID.RA-02', title: 'Risk Assessment - Threat Intelligence', description: 'Cyber threat intelligence is received and is used to understand threats.', priority: '2', control_type: 'technical' },
      { control_id: 'ID.RA-03', title: 'Risk Assessment - Risk Identification', description: 'Internal and external threats to the organization are identified and recorded.', priority: '1', control_type: 'strategic' },
      { control_id: 'ID.RA-04', title: 'Risk Assessment - Impact Analysis', description: 'Potential impacts and likelihoods of threats exploiting vulnerabilities are identified and recorded.', priority: '1', control_type: 'strategic' },
      { control_id: 'ID.IM-01', title: 'Improvement - Lessons Learned', description: 'Improvements are identified from evaluations, exercises, and operational activities.', priority: '3', control_type: 'organizational' },
      // PROTECT
      { control_id: 'PR.AA-01', title: 'Identity & Access - Identities Managed', description: 'Identities and credentials for authorized users, services, and hardware are managed by the organization.', priority: '1', control_type: 'technical' },
      { control_id: 'PR.AA-02', title: 'Identity & Access - Authentication', description: 'Identities are proofed and bound to credentials based on the context of interactions.', priority: '1', control_type: 'technical' },
      { control_id: 'PR.AA-03', title: 'Identity & Access - Remote Access', description: 'Users, services, and hardware are authenticated by the organization.', priority: '1', control_type: 'technical' },
      { control_id: 'PR.AA-04', title: 'Identity & Access - Access Permissions', description: 'Identity assertions and access permissions are managed, incorporated, and revoked.', priority: '1', control_type: 'technical' },
      { control_id: 'PR.AA-05', title: 'Identity & Access - Physical Access', description: 'Physical access to assets is managed, monitored, and enforced commensurate with risk.', priority: '2', control_type: 'physical' },
      { control_id: 'PR.AT-01', title: 'Awareness & Training - Users Trained', description: 'Personnel are provided cybersecurity awareness and training so they can perform their duties.', priority: '2', control_type: 'organizational' },
      { control_id: 'PR.AT-02', title: 'Awareness & Training - Privileged Users Trained', description: 'Privileged users understand their roles and responsibilities.', priority: '1', control_type: 'organizational' },
      { control_id: 'PR.DS-01', title: 'Data Security - Data at Rest Protected', description: 'The confidentiality, integrity, and availability of data-at-rest are protected.', priority: '1', control_type: 'technical' },
      { control_id: 'PR.DS-02', title: 'Data Security - Data in Transit Protected', description: 'The confidentiality, integrity, and availability of data-in-transit are protected.', priority: '1', control_type: 'technical' },
      { control_id: 'PR.DS-10', title: 'Data Security - Confidentiality', description: 'The confidentiality of data is protected by access control and encryption mechanisms.', priority: '1', control_type: 'technical' },
      { control_id: 'PR.DS-11', title: 'Data Security - Integrity', description: 'The integrity of data is maintained and validated using integrity checking mechanisms.', priority: '1', control_type: 'technical' },
      { control_id: 'PR.PS-01', title: 'Platform Security - Configuration Management', description: 'Configuration management practices are established and applied.', priority: '1', control_type: 'technical' },
      { control_id: 'PR.PS-02', title: 'Platform Security - Software Maintained', description: 'Software is maintained, replaced, and removed commensurate with risk.', priority: '1', control_type: 'technical' },
      { control_id: 'PR.PS-03', title: 'Platform Security - Hardware Maintained', description: 'Hardware is maintained, replaced, and removed commensurate with risk.', priority: '2', control_type: 'technical' },
      { control_id: 'PR.IR-01', title: 'Resilience - Backups Maintained', description: 'Backups of data are created, protected, maintained, and tested.', priority: '1', control_type: 'technical' },
      { control_id: 'PR.IR-02', title: 'Resilience - Recovery Procedures', description: 'Recovery assets and processes are established and managed.', priority: '1', control_type: 'technical' },
      // DETECT
      { control_id: 'DE.CM-01', title: 'Continuous Monitoring - Network Monitoring', description: 'Networks and network services are monitored to find potentially adverse events.', priority: '1', control_type: 'technical' },
      { control_id: 'DE.CM-02', title: 'Continuous Monitoring - Physical Environment', description: 'The physical environment is monitored to find potentially adverse events.', priority: '3', control_type: 'physical' },
      { control_id: 'DE.CM-03', title: 'Continuous Monitoring - Personnel Activity', description: 'Personnel activity and technology usage are monitored to find potentially adverse events.', priority: '2', control_type: 'technical' },
      { control_id: 'DE.CM-06', title: 'Continuous Monitoring - External Provider Activity', description: 'External service provider activities and services are monitored to find potentially adverse events.', priority: '2', control_type: 'technical' },
      { control_id: 'DE.CM-09', title: 'Continuous Monitoring - Computing Hardware', description: 'Computing hardware and firmware are monitored to find potentially adverse events.', priority: '2', control_type: 'technical' },
      { control_id: 'DE.AE-02', title: 'Adverse Event Analysis - Anomalies Analyzed', description: 'Potentially adverse events are analyzed to better understand associated activities.', priority: '1', control_type: 'technical' },
      { control_id: 'DE.AE-03', title: 'Adverse Event Analysis - Correlation & Enrichment', description: 'Information is correlated from multiple sources to achieve situational awareness.', priority: '2', control_type: 'technical' },
      { control_id: 'DE.AE-06', title: 'Adverse Event Analysis - Incident Declared', description: 'Information on adverse events is provided to authorized staff and tools.', priority: '1', control_type: 'organizational' },
      // RESPOND
      { control_id: 'RS.MA-01', title: 'Incident Management - IR Plan Executed', description: 'The incident response plan is executed in coordination with relevant third parties.', priority: '1', control_type: 'organizational' },
      { control_id: 'RS.MA-02', title: 'Incident Management - Triage Performed', description: 'Incident reports are triaged and validated to support prioritized response.', priority: '1', control_type: 'organizational' },
      { control_id: 'RS.MA-03', title: 'Incident Management - Incidents Categorized', description: 'Incidents are categorized and prioritized based on severity and impact.', priority: '2', control_type: 'organizational' },
      { control_id: 'RS.AN-03', title: 'Incident Analysis - Root Cause Determined', description: 'Analysis is performed to determine the root cause of incidents.', priority: '1', control_type: 'technical' },
      { control_id: 'RS.CO-02', title: 'Incident Reporting - Stakeholders Notified', description: 'Internal and external stakeholders are notified of incidents per reporting requirements.', priority: '1', control_type: 'organizational' },
      { control_id: 'RS.MI-01', title: 'Incident Mitigation - Containment Performed', description: 'Incidents are contained to prevent further damage.', priority: '1', control_type: 'technical' },
      { control_id: 'RS.MI-02', title: 'Incident Mitigation - Eradication Performed', description: 'Incidents are eradicated by eliminating the root cause and associated artifacts.', priority: '1', control_type: 'technical' },
      // RECOVER
      { control_id: 'RC.RP-01', title: 'Recovery Execution - Recovery Plan Executed', description: 'The recovery portion of the incident response plan is executed once initiated.', priority: '1', control_type: 'organizational' },
      { control_id: 'RC.RP-02', title: 'Recovery Execution - Recovery Verified', description: 'Recovery actions are verified to confirm successful restoration of operations.', priority: '1', control_type: 'technical' },
      { control_id: 'RC.CO-03', title: 'Recovery Communication - Recovery Status Shared', description: 'Recovery activities and progress are communicated to designated stakeholders.', priority: '2', control_type: 'organizational' },
    ]
  };
