// Auto-generated by scripts/import-oscal-800171.js from NIST's OSCAL
// catalog (usnistgov/oscal-content nist.gov/SP800-171/rev3). Withdrawn
// Rev 3 identifiers are omitted. Do not hand-edit -- re-run the importer.
// Catalog version: 1.1.0; last modified 2026-05-12T01:01:09.00000-00:00.
'use strict';

module.exports = {
  "version": "1.1.0",
  "controls": [
    {
      "control_id": "03.01.01",
      "title": "Account Management",
      "description": "a. Define the types of system accounts allowed and prohibited.\nb. Create, enable, modify, disable, and remove system accounts in accordance with policy, procedures, prerequisites, and criteria.\nc. Specify:\n  1. Authorized users of the system,\n  2. Group and role membership, and\n  3. Access authorizations (i.e., privileges) for each account.\nd. Authorize access to the system based on:\n  1. A valid access authorization and\n  2. Intended system usage.\ne. Monitor the use of system accounts.\nf. Disable system accounts when:\n  1. The accounts have expired,\n  2. The accounts have been inactive for [Assignment: organization-defined time period],\n  3. The accounts are no longer associated with a user or individual,\n  4. The accounts are in violation of organizational policy, or\n  5. Significant risks associated with individuals are discovered.\ng. Notify account managers and designated personnel or roles within:\n  1. [Assignment: organization-defined time period] when accounts are no longer required.\n  2. [Assignment: organization-defined time period] when users are terminated or transferred.\n  3. [Assignment: organization-defined time period] when system usage or the need-to-know changes for an individual.\nh. Require that users log out of the system after [Assignment: organization-defined time period] of expected inactivity or when [Assignment: organization-defined circumstances].",
      "priority": "1",
      "control_type": "technical",
      "family": "Access Control"
    },
    {
      "control_id": "03.01.02",
      "title": "Access Enforcement",
      "description": "Enforce approved authorizations for logical access to CUI and system resources in accordance with applicable access control policies.",
      "priority": "1",
      "control_type": "technical",
      "family": "Access Control"
    },
    {
      "control_id": "03.01.03",
      "title": "Information Flow Enforcement",
      "description": "Enforce approved authorizations for controlling the flow of CUI within the system and between connected systems.",
      "priority": "1",
      "control_type": "technical",
      "family": "Access Control"
    },
    {
      "control_id": "03.01.04",
      "title": "Separation of Duties",
      "description": "a. Identify the duties of individuals requiring separation.\nb. Define system access authorizations to support separation of duties.",
      "priority": "1",
      "control_type": "technical",
      "family": "Access Control"
    },
    {
      "control_id": "03.01.05",
      "title": "Least Privilege",
      "description": "a. Allow only authorized system access for users (or processes acting on behalf of users) that is necessary to accomplish assigned organizational tasks.\nb. Authorize access to [Assignment: organization-defined security functions] and [Assignment: organization-defined security-relevant information].\nc. Review the privileges assigned to roles or classes of users [Assignment: organization-defined frequency] to validate the need for such privileges.\nd. Reassign or remove privileges, as necessary.",
      "priority": "1",
      "control_type": "technical",
      "family": "Access Control"
    },
    {
      "control_id": "03.01.06",
      "title": "Least Privilege – Privileged Accounts",
      "description": "a. Restrict privileged accounts on the system to [Assignment: organization-defined personnel or roles]..\nb. Require that users (or roles) with privileged accounts use non-privileged accounts when accessing non-security functions or non-security information.",
      "priority": "1",
      "control_type": "technical",
      "family": "Access Control"
    },
    {
      "control_id": "03.01.07",
      "title": "Least Privilege – Privileged Functions",
      "description": "a. Prevent non-privileged users from executing privileged functions.\nb. Log the execution of privileged functions.",
      "priority": "1",
      "control_type": "technical",
      "family": "Access Control"
    },
    {
      "control_id": "03.01.08",
      "title": "Unsuccessful Logon Attempts",
      "description": "a. Enforce a limit of [Assignment: organization-defined number] consecutive invalid logon attempts by a user during a [Assignment: organization-defined time period].\nb. Automatically [Selection (one or more): lock the account or node for an [Assignment: organization-defined time period]; lock the account or node until released by an administrator; delay next logon prompt; notify system administrator; take other action] when the maximum number of unsuccessful attempts is exceeded.",
      "priority": "1",
      "control_type": "technical",
      "family": "Access Control"
    },
    {
      "control_id": "03.01.09",
      "title": "System Use Notification",
      "description": "Display a system use notification message with privacy and security notices consistent with applicable CUI rules before granting access to the system.",
      "priority": "1",
      "control_type": "technical",
      "family": "Access Control"
    },
    {
      "control_id": "03.01.10",
      "title": "Device Lock",
      "description": "a. Prevent access to the system by [Selection (one or more): initiating a device lock after [Assignment: organization-defined time period] of inactivity; requiring the user to initiate a device lock before leaving the system unattended].\nb. Retain the device lock until the user reestablishes access using established identification and authentication procedures.\nc. Conceal, via the device lock, information previously visible on the display with a publicly viewable image.",
      "priority": "1",
      "control_type": "technical",
      "family": "Access Control"
    },
    {
      "control_id": "03.01.11",
      "title": "Session Termination",
      "description": "Terminate a user session automatically after [Assignment: organization-defined conditions or trigger events requiring session disconnect].",
      "priority": "1",
      "control_type": "technical",
      "family": "Access Control"
    },
    {
      "control_id": "03.01.12",
      "title": "Remote Access",
      "description": "a. Establish usage restrictions, configuration requirements, and connection requirements for each type of allowable remote system access.\nb. Authorize each type of remote system access prior to establishing such connections.\nc. Route remote access to the system through authorized and managed access control points.\nd. Authorize the remote execution of privileged commands and remote access to security-relevant information.",
      "priority": "1",
      "control_type": "technical",
      "family": "Access Control"
    },
    {
      "control_id": "03.01.16",
      "title": "Wireless Access",
      "description": "a. Establish usage restrictions, configuration requirements, and connection requirements for each type of wireless access to the system.\nb. Authorize each type of wireless access to the system prior to establishing such connections.\nc. Disable, when not intended for use, wireless networking capabilities prior to issuance and deployment.\nd. Protect wireless access to the system using authentication and encryption.",
      "priority": "1",
      "control_type": "technical",
      "family": "Access Control"
    },
    {
      "control_id": "03.01.18",
      "title": "Access Control for Mobile Devices",
      "description": "a. Establish usage restrictions, configuration requirements, and connection requirements for mobile devices.\nb. Authorize the connection of mobile devices to the system.\nc. Implement full-device or container-based encryption to protect the confidentiality of CUI on mobile devices.",
      "priority": "1",
      "control_type": "technical",
      "family": "Access Control"
    },
    {
      "control_id": "03.01.20",
      "title": "Use of External Systems",
      "description": "a. Prohibit the use of external systems unless the systems are specifically authorized.\nb. Establish the following security requirements to be satisfied on external systems prior to allowing use of or access to those systems by authorized individuals: [Assignment: organization-defined security requirements].\nc. Permit authorized individuals to use external systems to access the organizational system or to process, store, or transmit CUI only after:\n  1. Verifying that the security requirements on the external systems as specified in the organization’s system security plans have been satisfied and\n  2. Retaining approved system connection or processing agreements with the organizational entities hosting the external systems.\nd. Restrict the use of organization-controlled portable storage devices by authorized individuals on external systems.",
      "priority": "1",
      "control_type": "technical",
      "family": "Access Control"
    },
    {
      "control_id": "03.01.22",
      "title": "Publicly Accessible Content",
      "description": "a. Train authorized individuals to ensure that publicly accessible information does not contain CUI.\nb. Review the content on publicly accessible systems for CUI and remove such information, if discovered.",
      "priority": "1",
      "control_type": "technical",
      "family": "Access Control"
    },
    {
      "control_id": "03.02.01",
      "title": "Literacy Training and Awareness",
      "description": "a. Provide security literacy training to system users:\n  1. As part of initial training for new users and [Assignment: organization-defined frequency] thereafter,\n  2. When required by system changes or following [Assignment: organization-defined events], and\n  3. On recognizing and reporting indicators of insider threat, social engineering, and social mining.\nb. Update security literacy training content [Assignment: organization-defined frequency] and following [Assignment: organization-defined events].",
      "priority": "2",
      "control_type": "organizational",
      "family": "Awareness and Training"
    },
    {
      "control_id": "03.02.02",
      "title": "Role-Based Training",
      "description": "a. Provide role-based security training to organizational personnel:\n  1. Before authorizing access to the system or CUI, before performing assigned duties, and [Assignment: organization-defined frequency] thereafter\n  2. When required by system changes or following [Assignment: organization-defined events].\nb. Update role-based training content [Assignment: organization-defined frequency] and following [Assignment: organization-defined events].",
      "priority": "2",
      "control_type": "organizational",
      "family": "Awareness and Training"
    },
    {
      "control_id": "03.03.01",
      "title": "Event Logging",
      "description": "a. Specify the following event types selected for logging within the system: [Assignment: organization-defined event types].\nb. Review and update the event types selected for logging [Assignment: organization-defined frequency].",
      "priority": "1",
      "control_type": "technical",
      "family": "Audit and Accountability"
    },
    {
      "control_id": "03.03.02",
      "title": "Audit Record Content",
      "description": "a. Include the following content in audit records:\n  1. What type of event occurred\n  2. When the event occurred\n  3. Where the event occurred\n  4. Source of the event\n  5. Outcome of the event\n  6. Identity of the individuals, subjects, objects, or entities associated with the event\nb. Provide additional information for audit records as needed.",
      "priority": "1",
      "control_type": "technical",
      "family": "Audit and Accountability"
    },
    {
      "control_id": "03.03.03",
      "title": "Audit Record Generation",
      "description": "a. Generate audit records for the selected event types and audit record content specified in 03.03.01 and 03.03.02.\nb. Retain audit records for a time period consistent with the records retention policy.",
      "priority": "1",
      "control_type": "technical",
      "family": "Audit and Accountability"
    },
    {
      "control_id": "03.03.04",
      "title": "Response to Audit Logging Process Failures",
      "description": "a. Alert organizational personnel or roles within [Assignment: organization-defined time period] in the event of an audit logging process failure.\nb. Take the following additional actions: [Assignment: organization-defined additional actions].",
      "priority": "1",
      "control_type": "technical",
      "family": "Audit and Accountability"
    },
    {
      "control_id": "03.03.05",
      "title": "Audit Record Review, Analysis, and Reporting",
      "description": "a. Review and analyze system audit records [Assignment: organization-defined frequency] for indications and the potential impact of inappropriate or unusual activity.\nb. Report findings to organizational personnel or roles.\nc. Analyze and correlate audit records across different repositories to gain organization-wide situational awareness.",
      "priority": "1",
      "control_type": "technical",
      "family": "Audit and Accountability"
    },
    {
      "control_id": "03.03.06",
      "title": "Audit Record Reduction and Report Generation",
      "description": "a. Implement an audit record reduction and report generation capability that supports audit record review, analysis, reporting requirements, and after-the-fact investigations of incidents.\nb. Preserve the original content and time ordering of audit records.",
      "priority": "1",
      "control_type": "technical",
      "family": "Audit and Accountability"
    },
    {
      "control_id": "03.03.07",
      "title": "Time Stamps",
      "description": "a. Use internal system clocks to generate time stamps for audit records.\nb. Record time stamps for audit records that meet [Assignment: organization-defined granularity of time measurement] and that use Coordinated Universal Time (UTC), have a fixed local time offset from UTC, or include the local time offset as part of the time stamp.",
      "priority": "1",
      "control_type": "technical",
      "family": "Audit and Accountability"
    },
    {
      "control_id": "03.03.08",
      "title": "Protection of Audit Information",
      "description": "a. Protect audit information and audit logging tools from unauthorized access, modification, and deletion.\nb. Authorize access to management of audit logging functionality to only a subset of privileged users or roles.",
      "priority": "1",
      "control_type": "technical",
      "family": "Audit and Accountability"
    },
    {
      "control_id": "03.04.01",
      "title": "Baseline Configuration",
      "description": "a. Develop and maintain under configuration control, a current baseline configuration of the system.\nb. Review and update the baseline configuration of the system [Assignment: organization-defined frequency] and when system components are installed or modified.",
      "priority": "2",
      "control_type": "technical",
      "family": "Configuration Management"
    },
    {
      "control_id": "03.04.02",
      "title": "Configuration Settings",
      "description": "a. Establish, document, and implement the following configuration settings for the system that reflect the most restrictive mode consistent with operational requirements: [Assignment: organization-defined configuration settings] .\nb. Identify, document, and approve any deviations from established configuration settings.",
      "priority": "2",
      "control_type": "technical",
      "family": "Configuration Management"
    },
    {
      "control_id": "03.04.03",
      "title": "Configuration Change Control",
      "description": "a. Define the types of changes to the system that are configuration-controlled.\nb. Review proposed configuration-controlled changes to the system, and approve or disapprove such changes with explicit consideration for security impacts.\nc. Implement and document approved configuration-controlled changes to the system.\nd. Monitor and review activities associated with configuration-controlled changes to the system.",
      "priority": "2",
      "control_type": "technical",
      "family": "Configuration Management"
    },
    {
      "control_id": "03.04.04",
      "title": "Impact Analyses",
      "description": "a. Analyze changes to the system to determine potential security impacts prior to change implementation.\nb. Verify that the security requirements for the system continue to be satisfied after the system changes have been implemented.",
      "priority": "2",
      "control_type": "technical",
      "family": "Configuration Management"
    },
    {
      "control_id": "03.04.05",
      "title": "Access Restrictions for Change",
      "description": "Define, document, approve, and enforce physical and logical access restrictions associated with changes to the system.",
      "priority": "2",
      "control_type": "technical",
      "family": "Configuration Management"
    },
    {
      "control_id": "03.04.06",
      "title": "Least Functionality",
      "description": "a. Configure the system to provide only mission-essential capabilities.\nb. Prohibit or restrict use of the following functions, ports, protocols, connections, and services: [Assignment: organization-defined functions, ports, protocols, connections, and services] .\nc. Review the system [Assignment: organization-defined frequency] to identify unnecessary or nonsecure functions, ports, protocols, connections, and services.\nd. Disable or remove functions, ports, protocols, connections, and services that are unnecessary or nonsecure.",
      "priority": "2",
      "control_type": "technical",
      "family": "Configuration Management"
    },
    {
      "control_id": "03.04.08",
      "title": "Authorized Software – Allow by Exception",
      "description": "a. Identify software programs authorized to execute on the system.\nb. Implement a deny-all, allow-by-exception policy for the execution of authorized software programs on the system.\nc. Review and update the list of authorized software programs [Assignment: organization-defined frequency].",
      "priority": "2",
      "control_type": "technical",
      "family": "Configuration Management"
    },
    {
      "control_id": "03.04.10",
      "title": "System Component Inventory",
      "description": "a. Develop and document an inventory of system components.\nb. Review and update the system component inventory [Assignment: organization-defined frequency].\nc. Update the system component inventory as part of installations, removals, and system updates.",
      "priority": "2",
      "control_type": "technical",
      "family": "Configuration Management"
    },
    {
      "control_id": "03.04.11",
      "title": "Information Location",
      "description": "a. Identify and document the location of CUI and the system components on which the information is processed and stored.\nb. Document changes to the system or system component location where CUI is processed and stored.",
      "priority": "2",
      "control_type": "technical",
      "family": "Configuration Management"
    },
    {
      "control_id": "03.04.12",
      "title": "System and Component Configuration for High-Risk Areas",
      "description": "a. Issue systems or system components with the following configurations to individuals traveling to high-risk locations: [Assignment: organization-defined system configurations].\nb. Apply the following security requirements to the systems or components when the individuals return from travel: [Assignment: organization-defined security requirements].",
      "priority": "2",
      "control_type": "technical",
      "family": "Configuration Management"
    },
    {
      "control_id": "03.05.01",
      "title": "User Identification and Authentication",
      "description": "a. Uniquely identify and authenticate system users, and associate that unique identification with processes acting on behalf of those users.\nb. Re-authenticate users when [Assignment: organization-defined circumstances or situations requiring re-authentication] .",
      "priority": "1",
      "control_type": "technical",
      "family": "Identification and Authentication"
    },
    {
      "control_id": "03.05.02",
      "title": "Device Identification and Authentication",
      "description": "Uniquely identify and authenticate [Assignment: organization-defined devices or types of devices] before establishing a system connection.",
      "priority": "1",
      "control_type": "technical",
      "family": "Identification and Authentication"
    },
    {
      "control_id": "03.05.03",
      "title": "Multi-Factor Authentication",
      "description": "Implement multi-factor authentication for access to privileged and non-privileged accounts.",
      "priority": "1",
      "control_type": "technical",
      "family": "Identification and Authentication"
    },
    {
      "control_id": "03.05.04",
      "title": "Replay-Resistant Authentication",
      "description": "Implement replay-resistant authentication mechanisms for access to privileged and non-privileged accounts.",
      "priority": "1",
      "control_type": "technical",
      "family": "Identification and Authentication"
    },
    {
      "control_id": "03.05.05",
      "title": "Identifier Management",
      "description": "a. Receive authorization from organizational personnel or roles to assign an individual, group, role, service, or device identifier.\nb. Select and assign an identifier that identifies an individual, group, role, service, or device.\nc. Prevent the reuse of identifiers for [Assignment: organization-defined time period].\nd. Manage individual identifiers by uniquely identifying each individual as [Assignment: organization-defined characteristic identifying individual status].",
      "priority": "1",
      "control_type": "technical",
      "family": "Identification and Authentication"
    },
    {
      "control_id": "03.05.07",
      "title": "Password Management",
      "description": "a. Maintain a list of commonly-used, expected, or compromised passwords, and update the list [Assignment: organization-defined frequency] and when organizational passwords are suspected to have been compromised.\nb. Verify that passwords are not found on the list of commonly used, expected, or compromised passwords when users create or update passwords.\nc. Transmit passwords only over cryptographically protected channels.\nd. Store passwords in a cryptographically protected form.\ne. Select a new password upon first use after account recovery.\nf. Enforce the following composition and complexity rules for passwords: [Assignment: organization-defined composition and complexity rules].",
      "priority": "1",
      "control_type": "technical",
      "family": "Identification and Authentication"
    },
    {
      "control_id": "03.05.11",
      "title": "Authentication Feedback",
      "description": "Obscure feedback of authentication information during the authentication process.",
      "priority": "1",
      "control_type": "technical",
      "family": "Identification and Authentication"
    },
    {
      "control_id": "03.05.12",
      "title": "Authenticator Management",
      "description": "a. Verify the identity of the individual, group, role, service, or device receiving the authenticator as part of the initial authenticator distribution.\nb. Establish initial authenticator content for any authenticators issued by the organization.\nc. Establish and implement administrative procedures for initial authenticator distribution; for lost, compromised, or damaged authenticators; and for revoking authenticators.\nd. Change default authenticators at first use.\ne. Change or refresh authenticators [Assignment: organization-defined frequency] or when the following events occur: [Assignment: organization-defined events].\nf. Protect authenticator content from unauthorized disclosure and modification.",
      "priority": "1",
      "control_type": "technical",
      "family": "Identification and Authentication"
    },
    {
      "control_id": "03.06.01",
      "title": "Incident Handling",
      "description": "Implement an incident-handling capability that is consistent with the incident response plan and includes preparation, detection and analysis, containment, eradication, and recovery.",
      "priority": "1",
      "control_type": "organizational",
      "family": "Incident Response"
    },
    {
      "control_id": "03.06.02",
      "title": "Incident Monitoring, Reporting, and Response Assistance",
      "description": "a. Track and document system security incidents.\nb. Report suspected incidents to the organizational incident response capability within [Assignment: organization-defined time period].\nc. Report incident information to [Assignment: organization-defined authorities].\nd. Provide an incident response support resource that offers advice and assistance to system users on handling and reporting incidents.",
      "priority": "1",
      "control_type": "organizational",
      "family": "Incident Response"
    },
    {
      "control_id": "03.06.03",
      "title": "Incident Response Testing",
      "description": "Test the effectiveness of the incident response capability [Assignment: organization-defined frequency].",
      "priority": "1",
      "control_type": "organizational",
      "family": "Incident Response"
    },
    {
      "control_id": "03.06.04",
      "title": "Incident Response Training",
      "description": "a. Provide incident response training to system users consistent with assigned roles and responsibilities:\n  1. Within [Assignment: organization-defined time period] of assuming an incident response role or responsibility or acquiring system access,\n  2. When required by system changes, and\n  3. [Assignment: organization-defined frequency] thereafter.\nb. Review and update incident response training content [Assignment: organization-defined frequency] and following [Assignment: organization-defined events].",
      "priority": "1",
      "control_type": "organizational",
      "family": "Incident Response"
    },
    {
      "control_id": "03.06.05",
      "title": "Incident Response Plan",
      "description": "a. Develop an incident response plan that:\n  1. Provides the organization with a roadmap for implementing its incident response capability,\n  2. Describes the structure and organization of the incident response capability,\n  3. Provides a high-level approach for how the incident response capability fits into the overall organization,\n  4. Defines reportable incidents,\n  5. Addresses the sharing of incident information, and\n  6. Designates responsibilities to organizational entities, personnel, or roles.\nb. Distribute copies of the incident response plan to designated incident response personnel (identified by name and/or by role) and organizational elements.\nc. Update the incident response plan to address system and organizational changes or problems encountered during plan implementation, execution, or testing.\nd. Protect the incident response plan from unauthorized disclosure.",
      "priority": "1",
      "control_type": "organizational",
      "family": "Incident Response"
    },
    {
      "control_id": "03.07.04",
      "title": "Maintenance Tools",
      "description": "a. Approve, control, and monitor the use of system maintenance tools.\nb. Check media with diagnostic and test programs for malicious code before it is used in the system.\nc. Prevent the removal of system maintenance equipment containing CUI by verifying that there is no CUI on the equipment, sanitizing or destroying the equipment, or retaining the equipment within the facility.",
      "priority": "2",
      "control_type": "organizational",
      "family": "Maintenance"
    },
    {
      "control_id": "03.07.05",
      "title": "Nonlocal Maintenance",
      "description": "a. Approve and monitor nonlocal maintenance and diagnostic activities.\nb. Implement multi-factor authentication and replay resistance in the establishment of nonlocal maintenance and diagnostic sessions.\nc. Terminate session and network connections when nonlocal maintenance is completed.",
      "priority": "2",
      "control_type": "organizational",
      "family": "Maintenance"
    },
    {
      "control_id": "03.07.06",
      "title": "Maintenance Personnel",
      "description": "a. Establish a process for maintenance personnel authorization.\nb. Maintain a list of authorized maintenance organizations or personnel.\nc. Verify that non-escorted personnel who perform maintenance on the system possess the required access authorizations.\nd. Designate organizational personnel with required access authorizations and technical competence to supervise the maintenance activities of personnel who do not possess the required access authorizations.",
      "priority": "2",
      "control_type": "organizational",
      "family": "Maintenance"
    },
    {
      "control_id": "03.08.01",
      "title": "Media Storage",
      "description": "Physically control and securely store system media that contain CUI.",
      "priority": "2",
      "control_type": "physical",
      "family": "Media Protection"
    },
    {
      "control_id": "03.08.02",
      "title": "Media Access",
      "description": "Restrict access to CUI on system media to authorized personnel or roles.",
      "priority": "2",
      "control_type": "physical",
      "family": "Media Protection"
    },
    {
      "control_id": "03.08.03",
      "title": "Media Sanitization",
      "description": "Sanitize system media that contain CUI prior to disposal, release out of organizational control, or release for reuse.",
      "priority": "2",
      "control_type": "physical",
      "family": "Media Protection"
    },
    {
      "control_id": "03.08.04",
      "title": "Media Marking",
      "description": "Mark system media that contain CUI to indicate distribution limitations, handling caveats, and applicable CUI markings.",
      "priority": "2",
      "control_type": "physical",
      "family": "Media Protection"
    },
    {
      "control_id": "03.08.05",
      "title": "Media Transport",
      "description": "a. Protect and control system media that contain CUI during transport outside of controlled areas.\nb. Maintain accountability of system media that contain CUI during transport outside of controlled areas.\nc. Document activities associated with the transport of system media that contain CUI.",
      "priority": "2",
      "control_type": "physical",
      "family": "Media Protection"
    },
    {
      "control_id": "03.08.07",
      "title": "Media Use",
      "description": "a. Restrict or prohibit the use of [Assignment: organization-defined types of system media].\nb. Prohibit the use of removable system media without an identifiable owner.",
      "priority": "2",
      "control_type": "physical",
      "family": "Media Protection"
    },
    {
      "control_id": "03.08.09",
      "title": "System Backup – Cryptographic Protection",
      "description": "a. Protect the confidentiality of backup information.\nb. Implement cryptographic mechanisms to prevent the unauthorized disclosure of CUI at backup storage locations.",
      "priority": "2",
      "control_type": "physical",
      "family": "Media Protection"
    },
    {
      "control_id": "03.09.01",
      "title": "Personnel Screening",
      "description": "a. Screen individuals prior to authorizing access to the system.\nb. Rescreen individuals in accordance with [Assignment: organization-defined conditions requiring rescreening].",
      "priority": "2",
      "control_type": "organizational",
      "family": "Personnel Security"
    },
    {
      "control_id": "03.09.02",
      "title": "Personnel Termination and Transfer",
      "description": "a. When individual employment is terminated:\n  1. Disable system access within [Assignment: organization-defined time period],\n  2. Terminate or revoke authenticators and credentials associated with the individual, and\n  3. Retrieve security-related system property.\nb. When individuals are reassigned or transferred to other positions in the organization:\n  1. Review and confirm the ongoing operational need for current logical and physical access authorizations to the system and facility, and\n  2. Modify access authorization to correspond with any changes in operational need.",
      "priority": "2",
      "control_type": "organizational",
      "family": "Personnel Security"
    },
    {
      "control_id": "03.10.01",
      "title": "Physical Access Authorizations",
      "description": "a. Develop, approve, and maintain a list of individuals with authorized access to the facility where the system resides.\nb. Issue authorization credentials for facility access.\nc. Review the facility access list [Assignment: organization-defined frequency].\nd. Remove individuals from the facility access list when access is no longer required.",
      "priority": "2",
      "control_type": "physical",
      "family": "Physical Protection"
    },
    {
      "control_id": "03.10.02",
      "title": "Monitoring Physical Access",
      "description": "a. Monitor physical access to the facility where the system resides to detect and respond to physical security incidents.\nb. Review physical access logs [Assignment: organization-defined frequency] and upon occurrence of [Assignment: organization-defined events or potential indications of events].",
      "priority": "2",
      "control_type": "physical",
      "family": "Physical Protection"
    },
    {
      "control_id": "03.10.06",
      "title": "Alternate Work Site",
      "description": "a. Determine alternate work sites allowed for use by employees.\nb. Employ the following security requirements at alternate work sites: [Assignment: organization-defined security requirements].",
      "priority": "2",
      "control_type": "physical",
      "family": "Physical Protection"
    },
    {
      "control_id": "03.10.07",
      "title": "Physical Access Control",
      "description": "a. Enforce physical access authorizations at entry and exit points to the facility where the system resides by:\n  1. Verifying individual physical access authorizations before granting access to the facility and\n  2. Controlling ingress and egress with physical access control systems, devices, or guards.\nb. Maintain physical access audit logs for entry or exit points.\nc. Escort visitors, and control visitor activity.\nd. Secure keys, combinations, and other physical access devices.\ne. Control physical access to output devices to prevent unauthorized individuals from obtaining access to CUI.",
      "priority": "2",
      "control_type": "physical",
      "family": "Physical Protection"
    },
    {
      "control_id": "03.10.08",
      "title": "Access Control for Transmission",
      "description": "Control physical access to system distribution and transmission lines within organizational facilities.",
      "priority": "2",
      "control_type": "physical",
      "family": "Physical Protection"
    },
    {
      "control_id": "03.11.01",
      "title": "Risk Assessment",
      "description": "a. Assess the risk (including supply chain risk) of unauthorized disclosure resulting from the processing, storage, or transmission of CUI.\nb. Update risk assessments [Assignment: organization-defined frequency].",
      "priority": "1",
      "control_type": "strategic",
      "family": "Risk Assessment"
    },
    {
      "control_id": "03.11.02",
      "title": "Vulnerability Monitoring and Scanning",
      "description": "a. Monitor and scan the system for vulnerabilities [Assignment: organization-defined frequency] and when new vulnerabilities affecting the system are identified.\nb. Remediate system vulnerabilities within [Assignment: organization-defined response times].\nc. Update system vulnerabilities to be scanned [Assignment: organization-defined frequency] and when new vulnerabilities are identified and reported.",
      "priority": "1",
      "control_type": "strategic",
      "family": "Risk Assessment"
    },
    {
      "control_id": "03.11.04",
      "title": "Risk Response",
      "description": "Respond to findings from security assessments, monitoring, and audits.",
      "priority": "1",
      "control_type": "strategic",
      "family": "Risk Assessment"
    },
    {
      "control_id": "03.12.01",
      "title": "Security Assessment",
      "description": "Assess the security requirements for the system and its environment of operation [Assignment: organization-defined frequency] to determine if the requirements have been satisfied.",
      "priority": "2",
      "control_type": "organizational",
      "family": "Security Assessment and Monitoring"
    },
    {
      "control_id": "03.12.02",
      "title": "Plan of Action and Milestones",
      "description": "a. Develop a plan of action and milestones for the system:\n  1. To document the planned remediation actions to correct weaknesses or deficiencies noted during security assessments and\n  2. To reduce or eliminate known system vulnerabilities.\nb. Update the existing plan of action and milestones based on the findings from:\n  1. Security assessments,\n  2. Audits or reviews, and\n  3. Continuous monitoring activities.",
      "priority": "2",
      "control_type": "organizational",
      "family": "Security Assessment and Monitoring"
    },
    {
      "control_id": "03.12.03",
      "title": "Continuous Monitoring",
      "description": "Develop and implement a system-level continuous monitoring strategy that includes ongoing monitoring and security assessments.",
      "priority": "2",
      "control_type": "organizational",
      "family": "Security Assessment and Monitoring"
    },
    {
      "control_id": "03.12.05",
      "title": "Information Exchange",
      "description": "a. Approve and manage the exchange of CUI between the system and other systems using [Selection (one or more): interconnection security agreements; information exchange security agreements; memoranda of understanding or agreement; service-level agreements; user agreements; non-disclosure agreements; other types of agreements].\nb. Document interface characteristics, security requirements, and responsibilities for each system as part of the exchange agreements.\nc. Review and update the exchange agreements [Assignment: organization-defined frequency].",
      "priority": "2",
      "control_type": "organizational",
      "family": "Security Assessment and Monitoring"
    },
    {
      "control_id": "03.13.01",
      "title": "Boundary Protection",
      "description": "a. Monitor and control communications at external managed interfaces to the system and key internal managed interfaces within the system.\nb. Implement subnetworks for publicly accessible system components that are physically or logically separated from internal networks.\nc. Connect to external systems only through managed interfaces that consist of boundary protection devices arranged in accordance with an organizational security architecture.",
      "priority": "1",
      "control_type": "technical",
      "family": "System and Communications Protection"
    },
    {
      "control_id": "03.13.04",
      "title": "Information in Shared System Resources",
      "description": "Prevent unauthorized and unintended information transfer via shared system resources.",
      "priority": "1",
      "control_type": "technical",
      "family": "System and Communications Protection"
    },
    {
      "control_id": "03.13.06",
      "title": "Network Communications – Deny by Default – Allow by Exception",
      "description": "Deny network communications traffic by default, and allow network communications traffic by exception.",
      "priority": "1",
      "control_type": "technical",
      "family": "System and Communications Protection"
    },
    {
      "control_id": "03.13.08",
      "title": "Transmission and Storage Confidentiality",
      "description": "Implement cryptographic mechanisms to prevent the unauthorized disclosure of CUI during transmission and while in storage.",
      "priority": "1",
      "control_type": "technical",
      "family": "System and Communications Protection"
    },
    {
      "control_id": "03.13.09",
      "title": "Network Disconnect",
      "description": "Terminate the network connection associated with a communications session at the end of the session or after [Assignment: organization-defined time period] of inactivity.",
      "priority": "1",
      "control_type": "technical",
      "family": "System and Communications Protection"
    },
    {
      "control_id": "03.13.10",
      "title": "Cryptographic Key Establishment and Management",
      "description": "Establish and manage cryptographic keys in the system in accordance with the following key management requirements: [Assignment: organization-defined requirements for key generation, distribution, storage, access, and destruction].",
      "priority": "1",
      "control_type": "technical",
      "family": "System and Communications Protection"
    },
    {
      "control_id": "03.13.11",
      "title": "Cryptographic Protection",
      "description": "Implement the following types of cryptography to protect the confidentiality of CUI: [Assignment: organization-defined types of cryptography].",
      "priority": "1",
      "control_type": "technical",
      "family": "System and Communications Protection"
    },
    {
      "control_id": "03.13.12",
      "title": "Collaborative Computing Devices and Applications",
      "description": "a. Prohibit the remote activation of collaborative computing devices and applications with the following exceptions: [Assignment: organization-defined exceptions where remote activation is to be allowed].\nb. Provide an explicit indication of use to users physically present at the devices.",
      "priority": "1",
      "control_type": "technical",
      "family": "System and Communications Protection"
    },
    {
      "control_id": "03.13.13",
      "title": "Mobile Code",
      "description": "a. Define acceptable mobile code and mobile code technologies.\nb. Authorize, monitor, and control the use of mobile code.",
      "priority": "1",
      "control_type": "technical",
      "family": "System and Communications Protection"
    },
    {
      "control_id": "03.13.15",
      "title": "Session Authenticity",
      "description": "Protect the authenticity of communications sessions.",
      "priority": "1",
      "control_type": "technical",
      "family": "System and Communications Protection"
    },
    {
      "control_id": "03.14.01",
      "title": "Flaw Remediation",
      "description": "a. Identify, report, and correct system flaws.\nb. Install security-relevant software and firmware updates within [Assignment: organization-defined time period] of the release of the updates.",
      "priority": "1",
      "control_type": "technical",
      "family": "System and Information Integrity"
    },
    {
      "control_id": "03.14.02",
      "title": "Malicious Code Protection",
      "description": "a. Implement malicious code protection mechanisms at system entry and exit points to detect and eradicate malicious code.\nb. Update malicious code protection mechanisms as new releases are available in accordance with configuration management policies and procedures.\nc. Configure malicious code protection mechanisms to:\n  1. Perform scans of the system [Assignment: organization-defined frequency] and real-time scans of files from external sources at endpoints or system entry and exit points as the files are downloaded, opened, or executed; and\n  2. Block malicious code, quarantine malicious code, or take other mitigation actions in response to malicious code detection.",
      "priority": "1",
      "control_type": "technical",
      "family": "System and Information Integrity"
    },
    {
      "control_id": "03.14.03",
      "title": "Security Alerts, Advisories, and Directives",
      "description": "a. Receive system security alerts, advisories, and directives from external organizations on an ongoing basis.\nb. Generate and disseminate internal system security alerts, advisories, and directives, as necessary.",
      "priority": "1",
      "control_type": "technical",
      "family": "System and Information Integrity"
    },
    {
      "control_id": "03.14.06",
      "title": "System Monitoring",
      "description": "a. Monitor the system to detect:\n  1. Attacks and indicators of potential attacks and\n  2. Unauthorized connections.\nb. Identify unauthorized use of the system.\nc. Monitor inbound and outbound communications traffic to detect unusual or unauthorized activities or conditions.",
      "priority": "1",
      "control_type": "technical",
      "family": "System and Information Integrity"
    },
    {
      "control_id": "03.14.08",
      "title": "Information Management and Retention",
      "description": "Manage and retain CUI within the system and CUI output from the system in accordance with applicable laws, Executive Orders, directives, regulations, policies, standards, guidelines, and operational requirements.",
      "priority": "1",
      "control_type": "technical",
      "family": "System and Information Integrity"
    },
    {
      "control_id": "03.15.01",
      "title": "Policy and Procedures",
      "description": "a. Develop, document, and disseminate to organizational personnel or roles the policies and procedures needed to satisfy the security requirements for the protection of CUI.\nb. Review and update policies and procedures [Assignment: organization-defined frequency].",
      "priority": "2",
      "control_type": "policy",
      "family": "Planning"
    },
    {
      "control_id": "03.15.02",
      "title": "System Security Plan",
      "description": "a. Develop a system security plan that:\n  1. Defines the constituent system components;\n  2. Identifies the information types processed, stored, and transmitted by the system;\n  3. Describes specific threats to the system that are of concern to the organization;\n  4. Describes the operational environment for the system and any dependencies on or connections to other systems or system components;\n  5. Provides an overview of the security requirements for the system;\n  6. Describes the safeguards in place or planned for meeting the security requirements;\n  7. Identifies individuals that fulfill system roles and responsibilities; and\n  8. Includes other relevant information necessary for the protection of CUI.\nb. Review and update the system security plan [Assignment: organization-defined frequency].\nc. Protect the system security plan from unauthorized disclosure.",
      "priority": "2",
      "control_type": "policy",
      "family": "Planning"
    },
    {
      "control_id": "03.15.03",
      "title": "Rules of Behavior",
      "description": "a. Establish rules that describe the responsibilities and expected behavior for system usage and protecting CUI.\nb. Provide rules to individuals who require access to the system.\nc. Receive a documented acknowledgement from individuals indicating that they have read, understand, and agree to abide by the rules of behavior before authorizing access to CUI and the system.\nd. Review and update the rules of behavior [Assignment: organization-defined frequency].",
      "priority": "2",
      "control_type": "policy",
      "family": "Planning"
    },
    {
      "control_id": "03.16.01",
      "title": "Security Engineering Principles",
      "description": "Apply the following systems security engineering principles to the development or modification of the system and system components: [Assignment: organization-defined systems security engineering principles].",
      "priority": "2",
      "control_type": "organizational",
      "family": "System and Services Acquisition"
    },
    {
      "control_id": "03.16.02",
      "title": "Unsupported System Components",
      "description": "a. Replace system components when support for the components is no longer available from the developer, vendor, or manufacturer.\nb. Provide options for risk mitigation or alternative sources for continued support for unsupported components that cannot be replaced.",
      "priority": "2",
      "control_type": "organizational",
      "family": "System and Services Acquisition"
    },
    {
      "control_id": "03.16.03",
      "title": "External System Services",
      "description": "a. Require the providers of external system services used for the processing, storage, or transmission of CUI to comply with the following security requirements: [Assignment: organization-defined security requirements].\nb. Define and document user roles and responsibilities with regard to external system services, including shared responsibilities with external service providers.\nc. Implement processes, methods, and techniques to monitor security requirement compliance by external service providers on an ongoing basis.",
      "priority": "2",
      "control_type": "organizational",
      "family": "System and Services Acquisition"
    },
    {
      "control_id": "03.17.01",
      "title": "Supply Chain Risk Management Plan",
      "description": "a. Develop a plan for managing supply chain risks associated with the research and development, design, manufacturing, acquisition, delivery, integration, operations, maintenance, and disposal of the system, system components, or system services.\nb. Review and update the supply chain risk management plan [Assignment: organization-defined frequency].\nc. Protect the supply chain risk management plan from unauthorized disclosure.",
      "priority": "2",
      "control_type": "organizational",
      "family": "Supply Chain Risk Management"
    },
    {
      "control_id": "03.17.02",
      "title": "Acquisition Strategies, Tools, and Methods",
      "description": "Develop and implement acquisition strategies, contract tools, and procurement methods to identify, protect against, and mitigate supply chain risks.",
      "priority": "2",
      "control_type": "organizational",
      "family": "Supply Chain Risk Management"
    },
    {
      "control_id": "03.17.03",
      "title": "Supply Chain Requirements and Processes",
      "description": "a. Establish a process for identifying and addressing weaknesses or deficiencies in the supply chain elements and processes.\nb. Enforce the following security requirements to protect against supply chain risks to the system, system components, or system services and to limit the harm or consequences from supply chain-related events: [Assignment: organization-defined security requirements].",
      "priority": "2",
      "control_type": "organizational",
      "family": "Supply Chain Risk Management"
    }
  ]
};
