module.exports = {
    code: 'soc2', name: 'SOC 2 Type II', version: '2022',
    category: 'Audit', tier_required: 'community',
    description: 'Trust Service Criteria for service organizations. Mapped to NIST 800-160 trustworthiness objectives.',
    controls: [
      { control_id: 'CC1.1', title: 'COSO Principle 1 - Integrity and Ethical Values', description: 'The entity demonstrates a commitment to integrity and ethical values.', priority: '1', control_type: 'organizational' },
      { control_id: 'CC1.2', title: 'COSO Principle 2 - Board Independence', description: 'The board of directors demonstrates independence from management and exercises oversight.', priority: '2', control_type: 'organizational' },
      { control_id: 'CC1.3', title: 'COSO Principle 3 - Management Authority', description: 'Management establishes structures, reporting lines, and appropriate authorities.', priority: '2', control_type: 'organizational' },
      { control_id: 'CC2.1', title: 'COSO Principle 13 - Quality Information', description: 'The entity obtains or generates and uses relevant, quality information to support internal control.', priority: '1', control_type: 'organizational' },
      { control_id: 'CC2.2', title: 'COSO Principle 14 - Internal Communication', description: 'The entity internally communicates information needed to support the functioning of internal control.', priority: '2', control_type: 'organizational' },
      { control_id: 'CC3.1', title: 'COSO Principle 6 - Risk Assessment Objectives', description: 'The entity specifies objectives with sufficient clarity to enable identification of risks.', priority: '1', control_type: 'strategic' },
      { control_id: 'CC3.2', title: 'COSO Principle 7 - Risk Identification', description: 'The entity identifies risks to the achievement of its objectives and analyzes them as a basis for management.', priority: '1', control_type: 'strategic' },
      { control_id: 'CC3.3', title: 'COSO Principle 8 - Fraud Risk', description: 'The entity considers the potential for fraud in assessing risks to achieving objectives.', priority: '2', control_type: 'strategic' },
      { control_id: 'CC3.4', title: 'COSO Principle 9 - Change Risk', description: 'The entity identifies and assesses changes that could significantly impact internal control.', priority: '2', control_type: 'strategic' },
      { control_id: 'CC4.1', title: 'COSO Principle 16 - Monitoring', description: 'The entity selects, develops, and performs ongoing evaluations to ascertain controls are present.', priority: '1', control_type: 'organizational' },
      { control_id: 'CC5.1', title: 'COSO Principle 10 - Control Selection', description: 'The entity selects and develops control activities that contribute to mitigating risks.', priority: '1', control_type: 'strategic' },
      { control_id: 'CC5.2', title: 'COSO Principle 11 - Technology Controls', description: 'The entity selects and develops general control activities over technology to support objectives.', priority: '1', control_type: 'technical' },
      { control_id: 'CC5.3', title: 'COSO Principle 12 - Control Deployment', description: 'The entity deploys control activities through policies that establish expectations and procedures.', priority: '1', control_type: 'technical' },
      { control_id: 'CC6.1', title: 'Logical and Physical Access - Access Controls', description: 'The entity implements logical access security software, infrastructure, and architectures.', priority: '1', control_type: 'technical' },
      { control_id: 'CC6.2', title: 'Logical and Physical Access - User Registration', description: 'Prior to issuing system credentials, the entity registers and authorizes new users.', priority: '1', control_type: 'technical' },
      { control_id: 'CC6.3', title: 'Logical and Physical Access - Role-Based Access', description: 'The entity authorizes, modifies, or removes access to data and assets based on roles.', priority: '1', control_type: 'technical' },
      { control_id: 'CC6.6', title: 'Logical and Physical Access - External Threats', description: 'The entity implements controls to prevent or detect and act upon unauthorized access.', priority: '1', control_type: 'technical' },
      { control_id: 'CC6.7', title: 'Logical and Physical Access - Data Transmission', description: 'The entity restricts the transmission of data to authorized external parties.', priority: '1', control_type: 'technical' },
      { control_id: 'CC6.8', title: 'Logical and Physical Access - Malicious Software', description: 'The entity implements controls to prevent or detect and act upon the introduction of malicious software.', priority: '1', control_type: 'technical' },
      { control_id: 'CC7.1', title: 'System Operations - Detection Mechanisms', description: 'The entity uses detection and monitoring procedures to identify changes to configurations and new vulnerabilities.', priority: '1', control_type: 'technical' },
      { control_id: 'CC7.2', title: 'System Operations - Anomaly Monitoring', description: 'The entity monitors system components for anomalies indicative of malicious acts and natural disasters.', priority: '1', control_type: 'technical' },
      { control_id: 'CC7.3', title: 'System Operations - Security Incident Evaluation', description: 'The entity evaluates security events to determine whether they could or have resulted in a failure.', priority: '1', control_type: 'organizational' },
      { control_id: 'CC7.4', title: 'System Operations - Incident Response', description: 'The entity responds to identified security incidents by executing a defined incident response program.', priority: '1', control_type: 'organizational' },
      { control_id: 'CC7.5', title: 'System Operations - Incident Recovery', description: 'The entity identifies, develops, and implements activities to recover from identified security incidents.', priority: '1', control_type: 'organizational' },
      { control_id: 'CC8.1', title: 'Change Management - Change Authorization', description: 'The entity authorizes, designs, develops, configures, and tests changes prior to implementation.', priority: '1', control_type: 'organizational' },
      { control_id: 'CC9.1', title: 'Risk Mitigation - Risk Identification', description: 'The entity identifies, selects, and develops risk mitigation activities for risks arising from operations.', priority: '1', control_type: 'strategic' },
      { control_id: 'CC9.2', title: 'Risk Mitigation - Vendor Management', description: 'The entity assesses and manages risks associated with vendors and business partners.', priority: '2', control_type: 'organizational' },
    ]
  };
