module.exports = {
    code: 'state_ai_governance', name: 'US State AI Governance Laws', version: '2025',
    category: 'AI Governance', tier_required: 'govcloud',
    description: 'Comprehensive coverage of enacted US state AI laws across 12+ jurisdictions: Colorado SB 205, Illinois AI Video Interview Act, NYC Local Law 144, California SB 942/AB 2013/AB 2885/AB 1008, Texas TRAIGA, Virginia HB 2048, Connecticut SB 2, Tennessee ELVIS Act, Utah SB 149, Washington SB 5838, Maryland HB 1281, and New York State AI legislation. Controls are crosswalked to NIST AI RMF so evidence collected once satisfies multiple jurisdictions.',
    controls: [
      // Colorado SB 205
      { control_id: 'CO-AI-1', title: 'CO SB 205 — High-Risk AI Impact Assessment', description: 'Before deploying a high-risk AI system, conduct and document an impact assessment covering intended purpose, known risks, measures to mitigate algorithmic discrimination, and a post-deployment monitoring plan. (Colo. Rev. Stat. § 6-1-1703)', priority: '1', control_type: 'strategic' },
      { control_id: 'CO-AI-2', title: 'CO SB 205 — Consumer Disclosure for Consequential Decisions', description: 'Provide clear, plain-language disclosure to consumers when a high-risk AI system is used to make a consequential decision (employment, education, financial services, housing, healthcare, insurance). Disclose data types used and purpose. (§ 6-1-1704)', priority: '1', control_type: 'policy' },
      { control_id: 'CO-AI-3', title: 'CO SB 205 — Algorithmic Discrimination Prevention', description: 'Implement reasonable care to protect consumers from known or reasonably foreseeable risks of algorithmic discrimination based on protected characteristics. Include bias testing before deployment and after material changes. (§ 6-1-1702)', priority: '1', control_type: 'strategic' },
      { control_id: 'CO-AI-4', title: 'CO SB 205 — Consumer Right to Appeal AI Decisions', description: 'Provide consumers an opportunity to appeal a consequential decision made by or with substantial assistance of a high-risk AI system, with a meaningful human review process and documented outcome. (§ 6-1-1705)', priority: '1', control_type: 'policy' },
      { control_id: 'CO-AI-5', title: 'CO SB 205 — Developer Documentation and Disclosure', description: 'AI developers must provide deployers with documentation of intended uses, known limitations, bias evaluation results, and required safeguards. Maintain version-controlled records and update on material changes. (§ 6-1-1706)', priority: '2', control_type: 'organizational' },
      // Illinois
      { control_id: 'IL-AI-1', title: 'IL AI Video Interview Act — Pre-Interview Consent', description: 'Before conducting an AI-analyzed video interview, notify applicants in writing that AI will be used to analyze the video and assess qualifications, explain how the AI works, and obtain express written consent. (430 ILCS 1/10)', priority: '1', control_type: 'policy' },
      { control_id: 'IL-AI-2', title: 'IL AI Video Interview Act — Video Data Destruction', description: 'Destroy the applicant\'s video interview recording and all AI-derived analysis within 30 days of a written destruction request. Share interview data only with parties whose expertise is needed to evaluate applicant fit. (430 ILCS 1/20)', priority: '1', control_type: 'technical' },
      { control_id: 'IL-AI-3', title: 'IL AI Video Interview Act — No Sole AI Screening', description: 'Do not use AI video interview analysis as the sole or primary basis to exclude an applicant from an in-person interview. Human review must be incorporated as a meaningful step. (430 ILCS 1/20(c))', priority: '1', control_type: 'policy' },
      { control_id: 'IL-AI-4', title: 'IL HB 3773 — AI in Employment Decision Transparency', description: 'For AI systems materially used in employment decisions (screening, promotion, termination), provide notice to affected employees and applicants, document factors the AI considers, and maintain decision audit logs for two years.', priority: '2', control_type: 'organizational' },
      // New York City — Local Law 144
      { control_id: 'NYC-AI-1', title: 'NYC LL 144 — Annual Independent Bias Audit of AEDT', description: 'Before using and annually thereafter, commission an independent bias audit of every Automated Employment Decision Tool (AEDT). Calculate selection rate and impact ratio by gender and race/ethnicity. Retain auditor qualifications. (NYC Admin. Code § 20-871)', priority: '1', control_type: 'organizational' },
      { control_id: 'NYC-AI-2', title: 'NYC LL 144 — Bias Audit Summary Publication', description: 'Post a clear summary of the most recent independent bias audit on the organization\'s website, including audit date, data source, and impact ratio results for each demographic category tested. (§ 20-872)', priority: '1', control_type: 'policy' },
      { control_id: 'NYC-AI-3', title: 'NYC LL 144 — Candidate Notification', description: 'For NYC-based roles, notify candidates at least 10 business days before applying an AEDT to their assessment. Offer an alternative selection process or reasonable accommodation upon request. (§ 20-872)', priority: '1', control_type: 'policy' },
      { control_id: 'NYC-AI-4', title: 'NYC LL 144 — Audit Record Retention', description: 'Retain bias audit reports, supporting data, and selection records for at least three years after the audit date to support regulatory inspection and potential legal discovery. (§ 20-872(c))', priority: '2', control_type: 'technical' },
      // California
      { control_id: 'CA-AI-1', title: 'CA SB 942 — AI Provenance and Watermarking', description: 'Generative AI providers must implement technical measures (C2PA watermarks, metadata) so AI-generated text, audio, video, and images can be identified. Consumers must be able to detect AI origin. (Cal. Bus. & Prof. Code § 22756)', priority: '1', control_type: 'technical' },
      { control_id: 'CA-AI-2', title: 'CA AB 2013 — Training Data Transparency Documentation', description: 'Publish a publicly accessible summary of training data for generative AI systems trained on data available after Jan 1, 2022. Document data sources, categories, and licensing status. (Cal. Bus. & Prof. Code § 22758)', priority: '1', control_type: 'policy' },
      { control_id: 'CA-AI-3', title: 'CA SB 896 — GenAI Risk Assessment for State Contracts', description: 'Organizations providing AI services to California state agencies must complete and disclose a risk assessment for generative AI deployments, including potential harms and mitigation measures prior to contract execution.', priority: '2', control_type: 'strategic' },
      { control_id: 'CA-AI-4', title: 'CA AB 302 — State Agency AI Use Transparency', description: 'Maintain a publicly available inventory of AI systems used in government operations, including purpose, risk level, training data sources, and human oversight procedures, submitted annually to the legislature.', priority: '2', control_type: 'organizational' },
      { control_id: 'CA-AI-5', title: 'CA AB 2885 — AI Statutory Definition Alignment', description: 'Apply California statutory definitions of "artificial intelligence" and "automated decision system" consistently across internal policies, vendor contracts, and public disclosures to ensure regulatory alignment.', priority: '3', control_type: 'policy' },
      { control_id: 'CA-AI-6', title: 'CA AB 1008 — AI-Derived Inferences as Personal Information', description: 'Treat AI-generated inferences, profiles, and predictions derived from personal information as personal information under CCPA/CPRA. Apply consumer rights (access, deletion, correction, opt-out) to AI-derived data.', priority: '1', control_type: 'technical' },
      // Texas — TRAIGA
      { control_id: 'TX-AI-1', title: 'TX TRAIGA — High-Risk AI Consumer Disclosure', description: 'Disclose to consumers when a high-risk AI system is used to make or substantially influence a consequential decision affecting them. Include data categories used, purpose, and a consumer inquiry contact. (Texas TRAIGA § 541.002)', priority: '1', control_type: 'policy' },
      { control_id: 'TX-AI-2', title: 'TX TRAIGA — Algorithmic Bias Risk Management Program', description: 'Implement a documented risk management policy and program for high-risk AI systems addressing known or foreseeable risks of algorithmic discrimination. Conduct pre-deployment testing by protected characteristic.', priority: '1', control_type: 'strategic' },
      { control_id: 'TX-AI-3', title: 'TX TRAIGA — Deployer Oversight and Monitoring', description: 'AI deployers must limit AI use to documented intended purposes, train personnel on AI risks and limitations, continuously monitor AI performance, and maintain audit records of consequential decision outcomes.', priority: '2', control_type: 'organizational' },
      // Virginia — HB 2048
      { control_id: 'VA-AI-1', title: 'VA HB 2048 — High-Risk AI Impact Assessment', description: 'Before deploying a high-risk AI system, complete a documented impact assessment identifying the system\'s purpose, risks to consumers, categories of data processed, and safeguards against algorithmic discrimination. (Va. Code Ann. § 59.1-578)', priority: '1', control_type: 'strategic' },
      { control_id: 'VA-AI-2', title: 'VA HB 2048 — Right to Opt-Out of AI Profiling', description: 'Provide Virginia consumers the right to opt-out of automated processing of personal data for profiling producing legal or significant effects. Implement an accessible opt-out mechanism and honor requests within required timeframes. (Va. Code Ann. § 59.1-574)', priority: '1', control_type: 'policy' },
      { control_id: 'VA-AI-3', title: 'VA HB 2048 — Human Review of Consequential AI Decisions', description: 'Implement a documented process for consumers to request human review of any consequential decision made through automated means. Automated processing may not be the sole basis for decisions without a human review option.', priority: '1', control_type: 'policy' },
      // Connecticut — SB 2
      { control_id: 'CT-AI-1', title: 'CT SB 2 — Developer Duty of Reasonable Care', description: 'AI developers of high-risk systems must use reasonable care in design, testing, and documentation to protect consumers from known or foreseeable risks of algorithmic discrimination based on protected class status.', priority: '1', control_type: 'strategic' },
      { control_id: 'CT-AI-2', title: 'CT SB 2 — Deployer Impact Assessment and Consumer Rights', description: 'Before deploying a high-risk AI system, complete an impact assessment and implement a governance program. Provide consumers notice of AI use in consequential decisions and a meaningful opportunity to appeal adverse outcomes.', priority: '1', control_type: 'organizational' },
      { control_id: 'CT-AI-3', title: 'CT SB 2 — Annual Compliance Disclosure to Attorney General', description: 'Submit an annual compliance summary of high-risk AI systems deployed, impact assessments completed, and any algorithmic discrimination incidents or consumer complaints to the Connecticut Attorney General.', priority: '2', control_type: 'organizational' },
      // Tennessee — ELVIS Act
      { control_id: 'TN-AI-1', title: 'TN ELVIS Act — AI Voice and Likeness Consent', description: 'Obtain explicit informed consent before using AI to replicate, simulate, or reproduce an individual\'s voice or likeness for commercial purposes. Applies to musicians, performers, and any identifiable individual. (Tenn. Code Ann. § 47-25-1101)', priority: '1', control_type: 'policy' },
      { control_id: 'TN-AI-2', title: 'TN ELVIS Act — Takedown and Removal Process', description: 'Establish and publish a process for individuals to submit takedown requests for unauthorized AI-generated replications of their voice or likeness. Acknowledge within 48 hours and remove within legally prescribed timeframes.', priority: '1', control_type: 'technical' },
      { control_id: 'TN-AI-3', title: 'TN ELVIS Act — Platform Safe Harbor Compliance', description: 'Platforms hosting AI-generated content must register a designated agent, implement compliant takedown procedures, and provide counter-notice processes to maintain safe harbor protections under the ELVIS Act.', priority: '2', control_type: 'organizational' },
      // Utah — SB 149
      { control_id: 'UT-AI-1', title: 'UT SB 149 — GenAI Disclosure in Regulated Occupations', description: 'Practitioners in regulated occupations (legal, healthcare, financial services) must clearly disclose to consumers when generative AI is used to provide services or advice, prior to service delivery. (Utah Code Ann. § 13-2-11)', priority: '1', control_type: 'policy' },
      { control_id: 'UT-AI-2', title: 'UT SB 149 — AI Chatbot Human Identity Disclosure', description: 'Operators of AI-powered conversational systems must disclose the AI nature of the service when a user sincerely inquires whether they are interacting with a human. Deceptive AI identity claims are prohibited. (Utah Code Ann. § 13-2-12)', priority: '1', control_type: 'policy' },
      { control_id: 'UT-AI-3', title: 'UT SB 149 — Consumer Protection Reporting', description: 'Report AI-related consumer complaints and significant incidents to the Utah Division of Consumer Protection as required. Maintain records sufficient to demonstrate compliance with reporting obligations.', priority: '3', control_type: 'organizational' },
      // Washington — SB 5838 / HB 1951
      { control_id: 'WA-AI-1', title: 'WA SB 5838 — Automated Decision System Inventory', description: 'Maintain a current inventory of automated decision systems used in consequential decisions affecting Washington residents. Document purpose, deployment context, affected populations, risk classification, and human oversight mechanisms.', priority: '1', control_type: 'organizational' },
      { control_id: 'WA-AI-2', title: 'WA SB 5838 — Impact Assessment and Public Notice', description: 'Conduct documented impact assessments for automated decision systems affecting Washington consumers in housing, employment, credit, education, and healthcare. Publish a public-facing summary of assessment results.', priority: '1', control_type: 'strategic' },
      { control_id: 'WA-AI-3', title: 'WA HB 1951 — AI in Employment Decision Disclosure', description: 'Disclose to Washington job applicants and employees when AI tools materially contribute to hiring, performance management, or termination decisions. Provide a documented human review option for individuals receiving adverse AI-assisted outcomes.', priority: '1', control_type: 'policy' },
      // Maryland — HB 1281
      { control_id: 'MD-AI-1', title: 'MD HB 1281 — Independent Bias Audit for Employment AEDT', description: 'Conduct an independent bias audit of automated decision tools used in employment decisions affecting Maryland residents before use and annually thereafter. Publish audit results and provide candidates notice before the tool is applied.', priority: '1', control_type: 'organizational' },
      { control_id: 'MD-AI-2', title: 'MD HB 1281 — Consumer Complaint Resolution Process', description: 'Establish and maintain a formal process for Maryland consumers to submit complaints about automated decision outcomes. Investigate and respond in writing within 30 days. Escalate unresolved complaints to the Maryland Attorney General as required.', priority: '2', control_type: 'policy' },
      // New York State
      { control_id: 'NY-AI-1', title: 'NY — Automated Decision System Transparency', description: 'Provide New York residents with plain-language explanations of how automated systems affect decisions about them, including data inputs, logic applied, confidence thresholds, and options to contest decisions or request human review.', priority: '1', control_type: 'policy' },
      { control_id: 'NY-AI-2', title: 'NY — AI Bias Reporting for High-Stakes Decisions', description: 'For AI systems making high-stakes decisions (employment, credit, housing, healthcare) affecting New York residents, conduct annual algorithmic bias evaluations and maintain reports available to state agencies upon request.', priority: '1', control_type: 'organizational' },
      // Cross-cutting multi-state controls
      { control_id: 'SAI-CORE-1', title: 'Multi-State AI Compliance Program', description: 'Establish a centralized AI compliance program tracking all applicable state AI laws by jurisdiction, with a compliance calendar, regulatory watch process, policy update procedure, and a designated compliance owner per active state.', priority: '1', control_type: 'strategic' },
      { control_id: 'SAI-CORE-2', title: 'Unified AI System Register', description: 'Maintain a unified register of all AI systems in use, documenting: jurisdictions of deployment, applicable state laws, risk classification, impact assessment status, bias audit dates, and assigned compliance owners.', priority: '1', control_type: 'organizational' },
      { control_id: 'SAI-CORE-3', title: 'Cross-State Algorithmic Fairness Controls', description: 'Implement baseline algorithmic fairness controls — protected-class disparity testing, impact ratio analysis, and corrective action procedures — sufficient to satisfy discrimination prohibitions in CO, TX, VA, CT, and WA simultaneously.', priority: '1', control_type: 'technical' },
      { control_id: 'SAI-CORE-4', title: 'AI Training Data Provenance Documentation', description: 'Document the origin, licensing status, consent basis, and data categories for all training data used in AI systems subject to CA AB 2013, VA, or CT transparency requirements. Maintain version history and make summaries publicly accessible.', priority: '2', control_type: 'technical' },
      { control_id: 'SAI-CORE-5', title: 'State-Level AI Consumer Rights Fulfillment', description: 'Implement operational workflows to fulfill AI-specific consumer rights across jurisdictions: right to access AI-derived inferences (CA/VA), right to appeal (CO/VA/CT), right to human review (NYC/WA), right to opt-out of AI profiling (VA/CO), and right to voice/likeness control (TN/CA).', priority: '1', control_type: 'policy' },
      { control_id: 'SAI-CORE-6', title: 'Regulatory Change Management for State AI Laws', description: 'Monitor state legislative and regulatory activity for AI laws across all 50 states. Update internal policies and controls within 90 days of new AI law enactments. Maintain a state-law tracking log updated at least quarterly.', priority: '2', control_type: 'strategic' },
    ]
  };
