-- Migration 162: Financial audit readiness content
--
-- Generated by scripts/generate-financial-audit-migration.js from
-- scripts/lib/frameworks/financialAudit.js. Do not edit by hand.
--
-- Why: ERP and federal financial-management customers are audited against
-- FISCAM, SOX 404 and OMB A-123, and the platform had only twelve summary
-- FISCAM controls and no COSO, SOX ITGC or A-123 content. This adds
-- 106 ControlWeave-authored controls:
--   * FISCAM: business process, interface and data management families, and
--     control activities (CWF- prefix) under every family
--   * COSO 2013: five components and seventeen principles (paraphrased)
--   * SOX IT general controls library
--   * OMB A-123 Appendix A readiness checklist
-- Identifiers are ControlWeave's own, not official numbering.
--
-- Idempotent: frameworks are matched on code, controls on (framework_id,
-- control_id); existing rows keep their ids so implementations and evidence
-- links are untouched. FISCAM additions are skipped when the fiscam framework
-- is not installed yet (seed-frameworks.js installs them with it).

DO $$
DECLARE
  fw_id UUID;
BEGIN
  SELECT id INTO fw_id FROM frameworks WHERE code = 'fiscam' ORDER BY created_at LIMIT 1;
  IF fw_id IS NULL THEN
    RAISE NOTICE 'fiscam framework not present; skipping FISCAM additions';
  ELSE
    INSERT INTO framework_controls (framework_id, control_id, title, description, control_type, priority)
    SELECT fw_id, v.control_id, v.title, v.description, v.control_type, v.priority
      FROM (VALUES
        ($cw$BP-1$cw$, $cw$Business Process Application Controls$cw$, $cw$Controls within financial applications that ensure transactions are authorized, complete, accurate and valid when entered, processed and reported.$cw$, $cw$technical$cw$, $cw$1$cw$, NULL),
        ($cw$IN-1$cw$, $cw$Interface Controls$cw$, $cw$Controls over data moving between financial systems so that transfers are complete, accurate and timely.$cw$, $cw$technical$cw$, $cw$1$cw$, NULL),
        ($cw$DM-1$cw$, $cw$Data Management System Controls$cw$, $cw$Controls over databases and data stores supporting financial applications, including direct data access and changes made outside the application.$cw$, $cw$technical$cw$, $cw$1$cw$, NULL),
        ($cw$CWF-SM-01$cw$, $cw$Security program documented and approved$cw$, $cw$An entity-wide security program covering financially significant systems is documented, approved by management and assigned an accountable owner.$cw$, $cw$strategic$cw$, $cw$1$cw$, $cw$SM-1$cw$),
        ($cw$CWF-SM-02$cw$, $cw$Security roles for financial systems assigned$cw$, $cw$Security responsibilities for each financially significant system (system owner, security officer, data owner) are assigned in writing.$cw$, $cw$organizational$cw$, $cw$1$cw$, $cw$SM-1$cw$),
        ($cw$CWF-SM-03$cw$, $cw$Security awareness for financial system users$cw$, $cw$Users of financial systems complete security awareness training on hire and at least annually, and completion is tracked.$cw$, $cw$organizational$cw$, $cw$1$cw$, $cw$SM-1$cw$),
        ($cw$CWF-SM-04$cw$, $cw$Periodic risk assessment of financial systems$cw$, $cw$Risks to financially significant systems are assessed at least annually and when significant changes occur, and results feed control selection.$cw$, $cw$strategic$cw$, $cw$1$cw$, $cw$SM-2$cw$),
        ($cw$CWF-SM-05$cw$, $cw$Inventory of financially significant systems$cw$, $cw$An inventory identifies each system, interface and data store that supports financial reporting, with its owner and hosting arrangement.$cw$, $cw$organizational$cw$, $cw$1$cw$, $cw$SM-2$cw$),
        ($cw$CWF-SM-06$cw$, $cw$Security policies reviewed$cw$, $cw$Security policies and procedures that apply to financial systems are reviewed and re-approved on a defined cycle.$cw$, $cw$policy$cw$, $cw$1$cw$, $cw$SM-3$cw$),
        ($cw$CWF-SM-07$cw$, $cw$Control weaknesses tracked to remediation$cw$, $cw$Identified control weaknesses are recorded with an owner, milestones and due dates, and are tracked until validated as closed.$cw$, $cw$organizational$cw$, $cw$1$cw$, $cw$SM-4$cw$),
        ($cw$CWF-SM-08$cw$, $cw$Service organization reports reviewed$cw$, $cw$Service organization control reports for hosted or outsourced financial processing are obtained, reviewed for exceptions, and complementary user entity controls are mapped to owners.$cw$, $cw$organizational$cw$, $cw$1$cw$, $cw$SM-4$cw$),
        ($cw$CWF-AC-01$cw$, $cw$Access provisioning approved$cw$, $cw$New or changed access to financial systems is requested and approved by the business owner before it is granted, and the approval is retained.$cw$, $cw$technical$cw$, $cw$1$cw$, $cw$AC-FM-1$cw$),
        ($cw$CWF-AC-02$cw$, $cw$Timely removal of access$cw$, $cw$Access for separated or transferred personnel is removed within a defined period, confirmed against HR records.$cw$, $cw$technical$cw$, $cw$1$cw$, $cw$AC-FM-1$cw$),
        ($cw$CWF-AC-03$cw$, $cw$Periodic user access recertification$cw$, $cw$Owners recertify user access and role assignments to financial systems at a defined frequency, and inappropriate access is removed.$cw$, $cw$technical$cw$, $cw$1$cw$, $cw$AC-FM-1$cw$),
        ($cw$CWF-AC-04$cw$, $cw$Shared and generic accounts controlled$cw$, $cw$Shared, generic and service accounts are prohibited or individually approved, assigned an owner and monitored.$cw$, $cw$technical$cw$, $cw$1$cw$, $cw$AC-FM-1$cw$),
        ($cw$CWF-AC-05$cw$, $cw$Least privilege role design$cw$, $cw$Roles and responsibilities in financial applications grant only the functions needed for each job and are documented.$cw$, $cw$technical$cw$, $cw$1$cw$, $cw$AC-FM-2$cw$),
        ($cw$CWF-AC-06$cw$, $cw$Privileged access restricted and monitored$cw$, $cw$Administrator and superuser access is limited to named individuals, and activity performed with it is logged and reviewed.$cw$, $cw$technical$cw$, $cw$1$cw$, $cw$AC-FM-2$cw$),
        ($cw$CWF-AC-07$cw$, $cw$Emergency access reviewed$cw$, $cw$Emergency or firefighter access is granted for a defined purpose and time, logged, and reviewed after use by someone independent of the user.$cw$, $cw$technical$cw$, $cw$1$cw$, $cw$AC-FM-2$cw$),
        ($cw$CWF-AC-08$cw$, $cw$Strong authentication for privileged and remote access$cw$, $cw$Privileged and remote access to financial systems requires multifactor authentication.$cw$, $cw$technical$cw$, $cw$1$cw$, $cw$AC-FM-3$cw$),
        ($cw$CWF-AC-09$cw$, $cw$Authentication settings configured$cw$, $cw$Password, lockout and session timeout settings in financial systems meet the organization policy and are checked periodically.$cw$, $cw$technical$cw$, $cw$1$cw$, $cw$AC-FM-3$cw$),
        ($cw$CWF-AC-10$cw$, $cw$Network protection of financial systems$cw$, $cw$Financial systems are segmented from untrusted networks and inbound access is limited to approved paths.$cw$, $cw$technical$cw$, $cw$1$cw$, $cw$AC-FM-4$cw$),
        ($cw$CWF-AC-11$cw$, $cw$Physical access to computing facilities$cw$, $cw$Physical access to facilities housing financial systems is restricted to authorized personnel and reviewed periodically.$cw$, $cw$technical$cw$, $cw$1$cw$, $cw$AC-FM-4$cw$),
        ($cw$CWF-AC-12$cw$, $cw$Security event logging and review$cw$, $cw$Security-relevant events in financial systems are logged, protected from alteration and reviewed.$cw$, $cw$technical$cw$, $cw$1$cw$, $cw$AC-FM-4$cw$),
        ($cw$CWF-CM-01$cw$, $cw$Changes authorized, tested and approved$cw$, $cw$Changes to financial applications and their configuration are authorized, tested and approved before they move to production.$cw$, $cw$technical$cw$, $cw$1$cw$, $cw$CC-1$cw$),
        ($cw$CWF-CM-02$cw$, $cw$Separation of development and production$cw$, $cw$Developers cannot move their own changes into production; migration is performed by a separate function or an automated pipeline with approvals.$cw$, $cw$technical$cw$, $cw$1$cw$, $cw$CC-1$cw$),
        ($cw$CWF-CM-03$cw$, $cw$Emergency changes documented$cw$, $cw$Emergency changes are documented and approved after the fact within a defined period.$cw$, $cw$technical$cw$, $cw$1$cw$, $cw$CC-1$cw$),
        ($cw$CWF-CM-04$cw$, $cw$Production changes reconciled to approvals$cw$, $cw$Changes detected in production are periodically reconciled to approved change records, and unmatched changes are investigated.$cw$, $cw$technical$cw$, $cw$1$cw$, $cw$CC-1$cw$),
        ($cw$CWF-CM-05$cw$, $cw$Baseline configurations maintained$cw$, $cw$Approved baseline configurations exist for financial system components and deviations are detected and resolved.$cw$, $cw$technical$cw$, $cw$1$cw$, $cw$CC-2$cw$),
        ($cw$CWF-CM-06$cw$, $cw$Vulnerabilities remediated$cw$, $cw$Financial system components are scanned for vulnerabilities and patched within defined timeframes based on severity.$cw$, $cw$technical$cw$, $cw$1$cw$, $cw$CC-2$cw$),
        ($cw$CWF-SD-01$cw$, $cw$Incompatible duties defined$cw$, $cw$A segregation of duties matrix identifies incompatible business functions for each financial process.$cw$, $cw$organizational$cw$, $cw$1$cw$, $cw$SC-1$cw$),
        ($cw$CWF-SD-02$cw$, $cw$Segregation enforced and monitored in applications$cw$, $cw$Application roles are designed so incompatible functions are not combined, and user assignments are analyzed for conflicts on a defined schedule.$cw$, $cw$technical$cw$, $cw$1$cw$, $cw$SC-1$cw$),
        ($cw$CWF-SD-03$cw$, $cw$Mitigating controls for accepted conflicts$cw$, $cw$Where a conflict is accepted, a documented mitigating control with an owner and frequency is performed and evidenced.$cw$, $cw$organizational$cw$, $cw$1$cw$, $cw$SC-1$cw$),
        ($cw$CWF-CP-01$cw$, $cw$Backups and restores tested$cw$, $cw$Financial data is backed up on a defined schedule and restoration is tested periodically.$cw$, $cw$technical$cw$, $cw$1$cw$, $cw$CP-FM-1$cw$),
        ($cw$CWF-CP-02$cw$, $cw$Contingency plan tested$cw$, $cw$The contingency plan for financial systems is tested at least annually and lessons learned are incorporated.$cw$, $cw$organizational$cw$, $cw$1$cw$, $cw$CP-FM-1$cw$),
        ($cw$CWF-CP-03$cw$, $cw$Batch jobs monitored$cw$, $cw$Scheduled jobs that process financial data are monitored, and failures are resolved and documented.$cw$, $cw$technical$cw$, $cw$1$cw$, $cw$CP-FM-1$cw$),
        ($cw$CWF-BP-01$cw$, $cw$Input validation$cw$, $cw$Application edit checks reject or flag incomplete, invalid or out-of-range financial data at entry.$cw$, $cw$technical$cw$, $cw$1$cw$, $cw$BP-1$cw$),
        ($cw$CWF-BP-02$cw$, $cw$Approval workflows and limits configured$cw$, $cw$Approval hierarchies and dollar limits for purchasing, payments and journal entries are configured as approved and changes are reviewed.$cw$, $cw$technical$cw$, $cw$1$cw$, $cw$BP-1$cw$),
        ($cw$CWF-BP-03$cw$, $cw$Master data changes reviewed$cw$, $cw$Changes to vendor, customer, employee and bank master data are approved and independently reviewed.$cw$, $cw$technical$cw$, $cw$1$cw$, $cw$BP-1$cw$),
        ($cw$CWF-BP-04$cw$, $cw$Three-way match enforced$cw$, $cw$Invoices are matched to purchase orders and receipts within configured tolerances before payment.$cw$, $cw$technical$cw$, $cw$1$cw$, $cw$BP-1$cw$),
        ($cw$CWF-BP-05$cw$, $cw$Duplicate invoice prevention$cw$, $cw$The application blocks or flags invoices that duplicate an existing vendor invoice number, amount or date.$cw$, $cw$technical$cw$, $cw$1$cw$, $cw$BP-1$cw$),
        ($cw$CWF-BP-06$cw$, $cw$Reports used in controls are reliable$cw$, $cw$System reports used to perform controls are validated for completeness and accuracy.$cw$, $cw$technical$cw$, $cw$1$cw$, $cw$BP-1$cw$),
        ($cw$CWF-IN-01$cw$, $cw$Interface completeness reconciled$cw$, $cw$Record counts and control totals are reconciled between sending and receiving systems for each financially significant interface.$cw$, $cw$technical$cw$, $cw$1$cw$, $cw$IN-1$cw$),
        ($cw$CWF-IN-02$cw$, $cw$Interface errors resolved$cw$, $cw$Interface errors and rejected records are monitored, corrected and resubmitted timely.$cw$, $cw$technical$cw$, $cw$1$cw$, $cw$IN-1$cw$),
        ($cw$CWF-DM-01$cw$, $cw$Direct data access restricted$cw$, $cw$Direct access to financial databases that bypasses the application is restricted to authorized administrators.$cw$, $cw$technical$cw$, $cw$1$cw$, $cw$DM-1$cw$),
        ($cw$CWF-DM-02$cw$, $cw$Direct data changes logged and reviewed$cw$, $cw$Changes made to financial data outside the application are logged, approved and reviewed.$cw$, $cw$technical$cw$, $cw$1$cw$, $cw$DM-1$cw$)
      ) AS v(control_id, title, description, control_type, priority, parent_code)
    ON CONFLICT (framework_id, control_id) DO UPDATE
      SET title = EXCLUDED.title, description = EXCLUDED.description, control_type = EXCLUDED.control_type;
  
    UPDATE framework_controls child
       SET parent_control_id = parent.id
      FROM (VALUES
        ($cw$CWF-SM-01$cw$, $cw$SM-1$cw$),
        ($cw$CWF-SM-02$cw$, $cw$SM-1$cw$),
        ($cw$CWF-SM-03$cw$, $cw$SM-1$cw$),
        ($cw$CWF-SM-04$cw$, $cw$SM-2$cw$),
        ($cw$CWF-SM-05$cw$, $cw$SM-2$cw$),
        ($cw$CWF-SM-06$cw$, $cw$SM-3$cw$),
        ($cw$CWF-SM-07$cw$, $cw$SM-4$cw$),
        ($cw$CWF-SM-08$cw$, $cw$SM-4$cw$),
        ($cw$CWF-AC-01$cw$, $cw$AC-FM-1$cw$),
        ($cw$CWF-AC-02$cw$, $cw$AC-FM-1$cw$),
        ($cw$CWF-AC-03$cw$, $cw$AC-FM-1$cw$),
        ($cw$CWF-AC-04$cw$, $cw$AC-FM-1$cw$),
        ($cw$CWF-AC-05$cw$, $cw$AC-FM-2$cw$),
        ($cw$CWF-AC-06$cw$, $cw$AC-FM-2$cw$),
        ($cw$CWF-AC-07$cw$, $cw$AC-FM-2$cw$),
        ($cw$CWF-AC-08$cw$, $cw$AC-FM-3$cw$),
        ($cw$CWF-AC-09$cw$, $cw$AC-FM-3$cw$),
        ($cw$CWF-AC-10$cw$, $cw$AC-FM-4$cw$),
        ($cw$CWF-AC-11$cw$, $cw$AC-FM-4$cw$),
        ($cw$CWF-AC-12$cw$, $cw$AC-FM-4$cw$),
        ($cw$CWF-CM-01$cw$, $cw$CC-1$cw$),
        ($cw$CWF-CM-02$cw$, $cw$CC-1$cw$),
        ($cw$CWF-CM-03$cw$, $cw$CC-1$cw$),
        ($cw$CWF-CM-04$cw$, $cw$CC-1$cw$),
        ($cw$CWF-CM-05$cw$, $cw$CC-2$cw$),
        ($cw$CWF-CM-06$cw$, $cw$CC-2$cw$),
        ($cw$CWF-SD-01$cw$, $cw$SC-1$cw$),
        ($cw$CWF-SD-02$cw$, $cw$SC-1$cw$),
        ($cw$CWF-SD-03$cw$, $cw$SC-1$cw$),
        ($cw$CWF-CP-01$cw$, $cw$CP-FM-1$cw$),
        ($cw$CWF-CP-02$cw$, $cw$CP-FM-1$cw$),
        ($cw$CWF-CP-03$cw$, $cw$CP-FM-1$cw$),
        ($cw$CWF-BP-01$cw$, $cw$BP-1$cw$),
        ($cw$CWF-BP-02$cw$, $cw$BP-1$cw$),
        ($cw$CWF-BP-03$cw$, $cw$BP-1$cw$),
        ($cw$CWF-BP-04$cw$, $cw$BP-1$cw$),
        ($cw$CWF-BP-05$cw$, $cw$BP-1$cw$),
        ($cw$CWF-BP-06$cw$, $cw$BP-1$cw$),
        ($cw$CWF-IN-01$cw$, $cw$IN-1$cw$),
        ($cw$CWF-IN-02$cw$, $cw$IN-1$cw$),
        ($cw$CWF-DM-01$cw$, $cw$DM-1$cw$),
        ($cw$CWF-DM-02$cw$, $cw$DM-1$cw$)
      ) AS v(control_id, parent_code)
      JOIN framework_controls parent ON parent.framework_id = fw_id AND parent.control_id = v.parent_code
     WHERE child.framework_id = fw_id AND child.control_id = v.control_id
       AND child.parent_control_id IS DISTINCT FROM parent.id;
  END IF;

  SELECT id INTO fw_id FROM frameworks WHERE code = $cw$coso_2013$cw$ ORDER BY created_at LIMIT 1;
  IF fw_id IS NULL THEN
    INSERT INTO frameworks (code, name, version, description, category, tier_required, is_active, coverage_status)
    VALUES ($cw$coso_2013$cw$, $cw$COSO Internal Control - Integrated Framework (2013)$cw$, $cw$2013$cw$, $cw$The five components and seventeen principles of effective internal control, paraphrased by ControlWeave. Used for entity-level control assessments under SOX 404 and OMB A-123. Points of focus are not included.$cw$, $cw$Financial Audit$cw$, $cw$community$cw$, true, $cw$core_controls$cw$)
    RETURNING id INTO fw_id;
  ELSE
    UPDATE frameworks
       SET name = $cw$COSO Internal Control - Integrated Framework (2013)$cw$, version = $cw$2013$cw$, description = $cw$The five components and seventeen principles of effective internal control, paraphrased by ControlWeave. Used for entity-level control assessments under SOX 404 and OMB A-123. Points of focus are not included.$cw$,
           category = $cw$Financial Audit$cw$, coverage_status = $cw$core_controls$cw$
     WHERE id = fw_id;
  END IF;

  INSERT INTO framework_controls (framework_id, control_id, title, description, control_type, priority)
  SELECT fw_id, v.control_id, v.title, v.description, v.control_type, v.priority
    FROM (VALUES
      ($cw$COSO-CE$cw$, $cw$Control Environment$cw$, $cw$The standards, processes and structures that provide the basis for carrying out internal control.$cw$, $cw$organizational$cw$, $cw$1$cw$, NULL),
      ($cw$COSO-P1$cw$, $cw$Principle 1: Commitment to integrity and ethical values$cw$, $cw$The organization shows a commitment to integrity and ethics, sets expectations through a code of conduct and addresses deviations.$cw$, $cw$organizational$cw$, $cw$1$cw$, $cw$COSO-CE$cw$),
      ($cw$COSO-P2$cw$, $cw$Principle 2: Independent board oversight$cw$, $cw$The board is independent of management and oversees the development and performance of internal control.$cw$, $cw$organizational$cw$, $cw$1$cw$, $cw$COSO-CE$cw$),
      ($cw$COSO-P3$cw$, $cw$Principle 3: Structures, reporting lines and authority$cw$, $cw$Management, with board oversight, sets structures, reporting lines and authorities to pursue objectives.$cw$, $cw$organizational$cw$, $cw$1$cw$, $cw$COSO-CE$cw$),
      ($cw$COSO-P4$cw$, $cw$Principle 4: Commitment to competence$cw$, $cw$The organization attracts, develops and retains competent people aligned with its objectives.$cw$, $cw$organizational$cw$, $cw$1$cw$, $cw$COSO-CE$cw$),
      ($cw$COSO-P5$cw$, $cw$Principle 5: Accountability$cw$, $cw$Individuals are held accountable for their internal control responsibilities.$cw$, $cw$organizational$cw$, $cw$1$cw$, $cw$COSO-CE$cw$),
      ($cw$COSO-RA$cw$, $cw$Risk Assessment$cw$, $cw$The process for identifying and analyzing risks to achieving objectives.$cw$, $cw$strategic$cw$, $cw$1$cw$, NULL),
      ($cw$COSO-P6$cw$, $cw$Principle 6: Suitable objectives$cw$, $cw$Objectives are specified clearly enough to identify and assess the risks to them.$cw$, $cw$strategic$cw$, $cw$1$cw$, $cw$COSO-RA$cw$),
      ($cw$COSO-P7$cw$, $cw$Principle 7: Risk identification and analysis$cw$, $cw$Risks to objectives are identified across the organization and analyzed to decide how they should be managed.$cw$, $cw$strategic$cw$, $cw$1$cw$, $cw$COSO-RA$cw$),
      ($cw$COSO-P8$cw$, $cw$Principle 8: Fraud risk$cw$, $cw$The potential for fraud is considered when assessing risks.$cw$, $cw$strategic$cw$, $cw$1$cw$, $cw$COSO-RA$cw$),
      ($cw$COSO-P9$cw$, $cw$Principle 9: Significant change$cw$, $cw$Changes that could significantly affect internal control are identified and assessed.$cw$, $cw$strategic$cw$, $cw$1$cw$, $cw$COSO-RA$cw$),
      ($cw$COSO-CA$cw$, $cw$Control Activities$cw$, $cw$The actions set by policies and procedures that help ensure management directives to mitigate risks are carried out.$cw$, $cw$technical$cw$, $cw$1$cw$, NULL),
      ($cw$COSO-P10$cw$, $cw$Principle 10: Control activities selected and developed$cw$, $cw$Control activities are selected and developed to reduce risks to acceptable levels.$cw$, $cw$technical$cw$, $cw$1$cw$, $cw$COSO-CA$cw$),
      ($cw$COSO-P11$cw$, $cw$Principle 11: General controls over technology$cw$, $cw$General control activities over technology are selected and developed to support objectives.$cw$, $cw$technical$cw$, $cw$1$cw$, $cw$COSO-CA$cw$),
      ($cw$COSO-P12$cw$, $cw$Principle 12: Policies and procedures$cw$, $cw$Control activities are deployed through policies that set expectations and procedures that put them into action.$cw$, $cw$policy$cw$, $cw$1$cw$, $cw$COSO-CA$cw$),
      ($cw$COSO-IC$cw$, $cw$Information and Communication$cw$, $cw$Obtaining, generating and sharing the information needed to carry out internal control.$cw$, $cw$organizational$cw$, $cw$1$cw$, NULL),
      ($cw$COSO-P13$cw$, $cw$Principle 13: Relevant, quality information$cw$, $cw$Relevant, quality information is obtained or generated and used to support internal control.$cw$, $cw$organizational$cw$, $cw$1$cw$, $cw$COSO-IC$cw$),
      ($cw$COSO-P14$cw$, $cw$Principle 14: Internal communication$cw$, $cw$Information about internal control objectives and responsibilities is communicated internally.$cw$, $cw$organizational$cw$, $cw$1$cw$, $cw$COSO-IC$cw$),
      ($cw$COSO-P15$cw$, $cw$Principle 15: External communication$cw$, $cw$Matters affecting internal control are communicated with external parties.$cw$, $cw$organizational$cw$, $cw$1$cw$, $cw$COSO-IC$cw$),
      ($cw$COSO-MA$cw$, $cw$Monitoring Activities$cw$, $cw$Ongoing and separate evaluations to confirm that each component of internal control is present and functioning.$cw$, $cw$organizational$cw$, $cw$1$cw$, NULL),
      ($cw$COSO-P16$cw$, $cw$Principle 16: Ongoing and separate evaluations$cw$, $cw$Ongoing and separate evaluations confirm whether the components of internal control are present and functioning.$cw$, $cw$organizational$cw$, $cw$1$cw$, $cw$COSO-MA$cw$),
      ($cw$COSO-P17$cw$, $cw$Principle 17: Deficiencies communicated$cw$, $cw$Internal control deficiencies are evaluated and communicated timely to those responsible for corrective action, including senior management and the board.$cw$, $cw$organizational$cw$, $cw$1$cw$, $cw$COSO-MA$cw$)
    ) AS v(control_id, title, description, control_type, priority, parent_code)
  ON CONFLICT (framework_id, control_id) DO UPDATE
    SET title = EXCLUDED.title, description = EXCLUDED.description, control_type = EXCLUDED.control_type;

  UPDATE framework_controls child
     SET parent_control_id = parent.id
    FROM (VALUES
      ($cw$COSO-P1$cw$, $cw$COSO-CE$cw$),
      ($cw$COSO-P2$cw$, $cw$COSO-CE$cw$),
      ($cw$COSO-P3$cw$, $cw$COSO-CE$cw$),
      ($cw$COSO-P4$cw$, $cw$COSO-CE$cw$),
      ($cw$COSO-P5$cw$, $cw$COSO-CE$cw$),
      ($cw$COSO-P6$cw$, $cw$COSO-RA$cw$),
      ($cw$COSO-P7$cw$, $cw$COSO-RA$cw$),
      ($cw$COSO-P8$cw$, $cw$COSO-RA$cw$),
      ($cw$COSO-P9$cw$, $cw$COSO-RA$cw$),
      ($cw$COSO-P10$cw$, $cw$COSO-CA$cw$),
      ($cw$COSO-P11$cw$, $cw$COSO-CA$cw$),
      ($cw$COSO-P12$cw$, $cw$COSO-CA$cw$),
      ($cw$COSO-P13$cw$, $cw$COSO-IC$cw$),
      ($cw$COSO-P14$cw$, $cw$COSO-IC$cw$),
      ($cw$COSO-P15$cw$, $cw$COSO-IC$cw$),
      ($cw$COSO-P16$cw$, $cw$COSO-MA$cw$),
      ($cw$COSO-P17$cw$, $cw$COSO-MA$cw$)
    ) AS v(control_id, parent_code)
    JOIN framework_controls parent ON parent.framework_id = fw_id AND parent.control_id = v.parent_code
   WHERE child.framework_id = fw_id AND child.control_id = v.control_id
     AND child.parent_control_id IS DISTINCT FROM parent.id;

  SELECT id INTO fw_id FROM frameworks WHERE code = $cw$sox_itgc$cw$ ORDER BY created_at LIMIT 1;
  IF fw_id IS NULL THEN
    INSERT INTO frameworks (code, name, version, description, category, tier_required, is_active, coverage_status)
    VALUES ($cw$sox_itgc$cw$, $cw$SOX IT General Controls (ControlWeave library)$cw$, $cw$2026$cw$, $cw$A starter library of IT general controls commonly relied on in SOX 404 audits, grouped into access to programs and data, program change, program development and computer operations. Written by ControlWeave; tailor it in the risk-control matrix.$cw$, $cw$Financial Audit$cw$, $cw$community$cw$, true, $cw$representative$cw$)
    RETURNING id INTO fw_id;
  ELSE
    UPDATE frameworks
       SET name = $cw$SOX IT General Controls (ControlWeave library)$cw$, version = $cw$2026$cw$, description = $cw$A starter library of IT general controls commonly relied on in SOX 404 audits, grouped into access to programs and data, program change, program development and computer operations. Written by ControlWeave; tailor it in the risk-control matrix.$cw$,
           category = $cw$Financial Audit$cw$, coverage_status = $cw$representative$cw$
     WHERE id = fw_id;
  END IF;

  INSERT INTO framework_controls (framework_id, control_id, title, description, control_type, priority)
  SELECT fw_id, v.control_id, v.title, v.description, v.control_type, v.priority
    FROM (VALUES
      ($cw$ITGC-APD$cw$, $cw$Access to Programs and Data$cw$, $cw$Only authorized users can access financially significant applications, databases and operating systems.$cw$, $cw$technical$cw$, $cw$1$cw$, NULL),
      ($cw$ITGC-APD-01$cw$, $cw$New user access approved$cw$, $cw$New access to in-scope systems is approved by an appropriate manager before provisioning.$cw$, $cw$technical$cw$, $cw$1$cw$, $cw$ITGC-APD$cw$),
      ($cw$ITGC-APD-02$cw$, $cw$Terminated user access removed$cw$, $cw$Access for terminated users is removed timely, validated against an HR termination listing.$cw$, $cw$technical$cw$, $cw$1$cw$, $cw$ITGC-APD$cw$),
      ($cw$ITGC-APD-03$cw$, $cw$User access reviewed$cw$, $cw$Application, database and operating system access is reviewed by owners at least quarterly for key systems.$cw$, $cw$technical$cw$, $cw$1$cw$, $cw$ITGC-APD$cw$),
      ($cw$ITGC-APD-04$cw$, $cw$Privileged access restricted$cw$, $cw$Privileged access is limited to appropriate IT personnel and reviewed periodically.$cw$, $cw$technical$cw$, $cw$1$cw$, $cw$ITGC-APD$cw$),
      ($cw$ITGC-APD-05$cw$, $cw$Password and authentication settings$cw$, $cw$Authentication settings for in-scope systems meet policy.$cw$, $cw$technical$cw$, $cw$1$cw$, $cw$ITGC-APD$cw$),
      ($cw$ITGC-APD-06$cw$, $cw$Segregation of duties in applications$cw$, $cw$Conflicting application functions are identified and either removed or mitigated.$cw$, $cw$technical$cw$, $cw$1$cw$, $cw$ITGC-APD$cw$),
      ($cw$ITGC-APD-07$cw$, $cw$Generic and service accounts$cw$, $cw$Generic and service accounts have an assigned owner and cannot be used interactively without approval.$cw$, $cw$technical$cw$, $cw$1$cw$, $cw$ITGC-APD$cw$),
      ($cw$ITGC-APD-08$cw$, $cw$Emergency access monitored$cw$, $cw$Use of emergency access IDs is logged and reviewed after each use.$cw$, $cw$technical$cw$, $cw$1$cw$, $cw$ITGC-APD$cw$),
      ($cw$ITGC-PC$cw$, $cw$Program Change$cw$, $cw$Changes to in-scope systems are authorized, tested and approved.$cw$, $cw$technical$cw$, $cw$1$cw$, NULL),
      ($cw$ITGC-PC-01$cw$, $cw$Change requests approved$cw$, $cw$Changes are requested and approved by the business before development begins.$cw$, $cw$technical$cw$, $cw$1$cw$, $cw$ITGC-PC$cw$),
      ($cw$ITGC-PC-02$cw$, $cw$Changes tested$cw$, $cw$Changes are tested and user acceptance is documented before deployment.$cw$, $cw$technical$cw$, $cw$1$cw$, $cw$ITGC-PC$cw$),
      ($cw$ITGC-PC-03$cw$, $cw$Deployment approved$cw$, $cw$Deployment to production is approved and performed by someone other than the developer.$cw$, $cw$technical$cw$, $cw$1$cw$, $cw$ITGC-PC$cw$),
      ($cw$ITGC-PC-04$cw$, $cw$Emergency changes$cw$, $cw$Emergency changes are approved after deployment within a defined period.$cw$, $cw$technical$cw$, $cw$1$cw$, $cw$ITGC-PC$cw$),
      ($cw$ITGC-PC-05$cw$, $cw$Configuration changes$cw$, $cw$Changes to financially significant configuration (approval limits, tolerances, posting rules) follow the change process.$cw$, $cw$technical$cw$, $cw$1$cw$, $cw$ITGC-PC$cw$),
      ($cw$ITGC-PC-06$cw$, $cw$Change monitoring$cw$, $cw$System-generated change logs are compared to approved changes.$cw$, $cw$technical$cw$, $cw$1$cw$, $cw$ITGC-PC$cw$),
      ($cw$ITGC-PD$cw$, $cw$Program Development$cw$, $cw$New systems and major upgrades are acquired and implemented with appropriate controls.$cw$, $cw$technical$cw$, $cw$1$cw$, NULL),
      ($cw$ITGC-PD-01$cw$, $cw$Implementation approved$cw$, $cw$System implementations and major upgrades are approved and managed under a documented methodology.$cw$, $cw$technical$cw$, $cw$1$cw$, $cw$ITGC-PD$cw$),
      ($cw$ITGC-PD-02$cw$, $cw$Data conversion validated$cw$, $cw$Data converted into new systems is reconciled for completeness and accuracy.$cw$, $cw$technical$cw$, $cw$1$cw$, $cw$ITGC-PD$cw$),
      ($cw$ITGC-PD-03$cw$, $cw$Go-live approved$cw$, $cw$Go-live is approved by business and IT owners after testing.$cw$, $cw$technical$cw$, $cw$1$cw$, $cw$ITGC-PD$cw$),
      ($cw$ITGC-CO$cw$, $cw$Computer Operations$cw$, $cw$Processing, backups and incidents for in-scope systems are managed.$cw$, $cw$technical$cw$, $cw$1$cw$, NULL),
      ($cw$ITGC-CO-01$cw$, $cw$Job scheduling changes controlled$cw$, $cw$Changes to scheduled jobs are authorized.$cw$, $cw$technical$cw$, $cw$1$cw$, $cw$ITGC-CO$cw$),
      ($cw$ITGC-CO-02$cw$, $cw$Job failures resolved$cw$, $cw$Failed jobs are identified, resolved and documented.$cw$, $cw$technical$cw$, $cw$1$cw$, $cw$ITGC-CO$cw$),
      ($cw$ITGC-CO-03$cw$, $cw$Backups performed$cw$, $cw$Backups are performed and failures are resolved.$cw$, $cw$technical$cw$, $cw$1$cw$, $cw$ITGC-CO$cw$),
      ($cw$ITGC-CO-04$cw$, $cw$Restores tested$cw$, $cw$Restoration from backup is tested periodically.$cw$, $cw$technical$cw$, $cw$1$cw$, $cw$ITGC-CO$cw$),
      ($cw$ITGC-CO-05$cw$, $cw$Incidents managed$cw$, $cw$Incidents affecting in-scope systems are logged, prioritized and resolved.$cw$, $cw$technical$cw$, $cw$1$cw$, $cw$ITGC-CO$cw$)
    ) AS v(control_id, title, description, control_type, priority, parent_code)
  ON CONFLICT (framework_id, control_id) DO UPDATE
    SET title = EXCLUDED.title, description = EXCLUDED.description, control_type = EXCLUDED.control_type;

  UPDATE framework_controls child
     SET parent_control_id = parent.id
    FROM (VALUES
      ($cw$ITGC-APD-01$cw$, $cw$ITGC-APD$cw$),
      ($cw$ITGC-APD-02$cw$, $cw$ITGC-APD$cw$),
      ($cw$ITGC-APD-03$cw$, $cw$ITGC-APD$cw$),
      ($cw$ITGC-APD-04$cw$, $cw$ITGC-APD$cw$),
      ($cw$ITGC-APD-05$cw$, $cw$ITGC-APD$cw$),
      ($cw$ITGC-APD-06$cw$, $cw$ITGC-APD$cw$),
      ($cw$ITGC-APD-07$cw$, $cw$ITGC-APD$cw$),
      ($cw$ITGC-APD-08$cw$, $cw$ITGC-APD$cw$),
      ($cw$ITGC-PC-01$cw$, $cw$ITGC-PC$cw$),
      ($cw$ITGC-PC-02$cw$, $cw$ITGC-PC$cw$),
      ($cw$ITGC-PC-03$cw$, $cw$ITGC-PC$cw$),
      ($cw$ITGC-PC-04$cw$, $cw$ITGC-PC$cw$),
      ($cw$ITGC-PC-05$cw$, $cw$ITGC-PC$cw$),
      ($cw$ITGC-PC-06$cw$, $cw$ITGC-PC$cw$),
      ($cw$ITGC-PD-01$cw$, $cw$ITGC-PD$cw$),
      ($cw$ITGC-PD-02$cw$, $cw$ITGC-PD$cw$),
      ($cw$ITGC-PD-03$cw$, $cw$ITGC-PD$cw$),
      ($cw$ITGC-CO-01$cw$, $cw$ITGC-CO$cw$),
      ($cw$ITGC-CO-02$cw$, $cw$ITGC-CO$cw$),
      ($cw$ITGC-CO-03$cw$, $cw$ITGC-CO$cw$),
      ($cw$ITGC-CO-04$cw$, $cw$ITGC-CO$cw$),
      ($cw$ITGC-CO-05$cw$, $cw$ITGC-CO$cw$)
    ) AS v(control_id, parent_code)
    JOIN framework_controls parent ON parent.framework_id = fw_id AND parent.control_id = v.parent_code
   WHERE child.framework_id = fw_id AND child.control_id = v.control_id
     AND child.parent_control_id IS DISTINCT FROM parent.id;

  SELECT id INTO fw_id FROM frameworks WHERE code = $cw$omb_a123_appa$cw$ ORDER BY created_at LIMIT 1;
  IF fw_id IS NULL THEN
    INSERT INTO frameworks (code, name, version, description, category, tier_required, is_active, coverage_status)
    VALUES ($cw$omb_a123_appa$cw$, $cw$OMB A-123 Appendix A Readiness (ControlWeave checklist)$cw$, $cw$2018$cw$, $cw$Readiness activities a federal agency performs to assess internal control over reporting and support its annual Statement of Assurance. A ControlWeave checklist, not the circular text.$cw$, $cw$Financial Audit$cw$, $cw$community$cw$, true, $cw$representative$cw$)
    RETURNING id INTO fw_id;
  ELSE
    UPDATE frameworks
       SET name = $cw$OMB A-123 Appendix A Readiness (ControlWeave checklist)$cw$, version = $cw$2018$cw$, description = $cw$Readiness activities a federal agency performs to assess internal control over reporting and support its annual Statement of Assurance. A ControlWeave checklist, not the circular text.$cw$,
           category = $cw$Financial Audit$cw$, coverage_status = $cw$representative$cw$
     WHERE id = fw_id;
  END IF;

  INSERT INTO framework_controls (framework_id, control_id, title, description, control_type, priority)
  SELECT fw_id, v.control_id, v.title, v.description, v.control_type, v.priority
    FROM (VALUES
      ($cw$A123-01$cw$, $cw$Governance and senior assessment team$cw$, $cw$A senior assessment team or equivalent governs the assessment, approves scope and reviews results.$cw$, $cw$organizational$cw$, $cw$1$cw$, NULL),
      ($cw$A123-02$cw$, $cw$Scope and materiality$cw$, $cw$Materiality is set and significant financial reports, line items and disclosures are identified.$cw$, $cw$strategic$cw$, $cw$1$cw$, NULL),
      ($cw$A123-03$cw$, $cw$Assessable units defined$cw$, $cw$Significant processes and the components that execute them are defined as assessable units with owners.$cw$, $cw$organizational$cw$, $cw$1$cw$, NULL),
      ($cw$A123-04$cw$, $cw$Entity-level controls assessed$cw$, $cw$Entity-level controls are evaluated against the five components and seventeen principles.$cw$, $cw$organizational$cw$, $cw$1$cw$, NULL),
      ($cw$A123-05$cw$, $cw$Processes documented$cw$, $cw$Each significant process is documented with narratives or flowcharts showing key controls and systems.$cw$, $cw$organizational$cw$, $cw$1$cw$, NULL),
      ($cw$A123-06$cw$, $cw$Risks assessed by assertion$cw$, $cw$Risks of material misstatement are identified for each significant process and mapped to financial statement assertions.$cw$, $cw$strategic$cw$, $cw$1$cw$, NULL),
      ($cw$A123-07$cw$, $cw$Key controls identified$cw$, $cw$Key controls addressing each risk are identified in a risk-control matrix, including IT general and application controls.$cw$, $cw$organizational$cw$, $cw$1$cw$, NULL),
      ($cw$A123-08$cw$, $cw$Test of design$cw$, $cw$The design of each key control is evaluated, typically by walkthrough.$cw$, $cw$organizational$cw$, $cw$1$cw$, NULL),
      ($cw$A123-09$cw$, $cw$Test of operating effectiveness$cw$, $cw$Key controls are tested using documented sample sizes and results are retained.$cw$, $cw$organizational$cw$, $cw$1$cw$, NULL),
      ($cw$A123-10$cw$, $cw$Service organizations$cw$, $cw$Controls performed by service organizations are covered by service auditor reports or direct testing.$cw$, $cw$organizational$cw$, $cw$1$cw$, NULL),
      ($cw$A123-11$cw$, $cw$Deficiencies evaluated and aggregated$cw$, $cw$Exceptions are evaluated individually and in aggregate and classified as control deficiencies, significant deficiencies or material weaknesses.$cw$, $cw$organizational$cw$, $cw$1$cw$, NULL),
      ($cw$A123-12$cw$, $cw$Corrective action plans$cw$, $cw$Corrective action plans with milestones and owners are tracked for each deficiency and validated when complete.$cw$, $cw$organizational$cw$, $cw$1$cw$, NULL),
      ($cw$A123-13$cw$, $cw$Statement of Assurance support$cw$, $cw$Assessment results are summarized to support the annual Statement of Assurance, with material weaknesses reported.$cw$, $cw$organizational$cw$, $cw$1$cw$, NULL)
    ) AS v(control_id, title, description, control_type, priority, parent_code)
  ON CONFLICT (framework_id, control_id) DO UPDATE
    SET title = EXCLUDED.title, description = EXCLUDED.description, control_type = EXCLUDED.control_type;
END $$;

SELECT 'Migration 162 completed.' AS result;
