// @tier: community
'use strict';

/**
 * License Service
 *
 * Validates signed license keys that unlock Pro/Enterprise features.
 *
 * License key format:
 *   v1.<base64url(JSON payload)>.<HMAC-SHA256 hex signature>
 *
 * Payload fields:
 *   licensee  {string}  - Name of the licensed organization
 *   tier      {string}  - 'pro' | 'enterprise' | 'govcloud'
 *   seats     {number}  - Number of licensed seats (-1 = unlimited)
 *   iat       {number}  - Unix timestamp: issued-at
 *   exp       {number|null} - Unix timestamp: expires-at (null = perpetual)
 *
 * The HMAC is computed over the string "v1.<base64url payload>" using the
 * LICENSE_SECRET environment variable as the key.  Keys are generated by
 * ControlWeave and distributed to customers.
 */

const crypto = require('crypto');

const LICENSE_VERSION = 'v1';
const VALID_TIERS = Object.freeze(['pro', 'enterprise', 'govcloud']);

/**
 * In-memory cache for the currently active license.
 * Set by setActiveLicense() and read by getActiveLicense().
 * Avoids mutating process.env at runtime.
 */
let _activeLicense = null;

/**
 * Returns the signing secret.  In production this must be set via the
 * LICENSE_SECRET environment variable; the fallback is intentionally weak so
 * that self-generated test keys never validate on a real deployment.
 */
function getSecret() {
  return process.env.LICENSE_SECRET || 'controlweave-ce-license-v1-dev';
}

/**
 * Compute the expected HMAC for the given base64url-encoded payload segment.
 *
 * @param {string} payloadB64 - The base64url-encoded payload string (no dots)
 * @returns {string} 64-character lower-case hex string
 */
function computeSignature(payloadB64) {
  return crypto
    .createHmac('sha256', getSecret())
    .update(`${LICENSE_VERSION}.${payloadB64}`)
    .digest('hex');
}

/**
 * Parse and validate a license key string.
 *
 * @param {string} key - The raw license key (e.g. "v1.eyJ....<hex>")
 * @returns {{ valid: boolean, licensee?: string, tier?: string, seats?: number,
 *             issuedAt?: number|null, expiresAt?: number|null, error?: string }}
 */
function parseLicenseKey(key) {
  if (!key || typeof key !== 'string') {
    return { valid: false, error: 'No license key provided' };
  }

  const parts = key.trim().split('.');
  if (parts.length !== 3 || parts[0] !== LICENSE_VERSION) {
    return { valid: false, error: 'Invalid license key format' };
  }

  const [, payloadB64, signature] = parts;

  // Validate hex signature length (SHA-256 → 64 hex chars)
  if (!/^[0-9a-f]{64}$/i.test(signature)) {
    return { valid: false, error: 'Invalid license key signature format' };
  }

  // Constant-time HMAC comparison
  const expected = computeSignature(payloadB64);
  try {
    if (!crypto.timingSafeEqual(
      Buffer.from(expected, 'hex'),
      Buffer.from(signature.toLowerCase(), 'hex')
    )) {
      return { valid: false, error: 'Invalid license key signature' };
    }
  } catch {
    return { valid: false, error: 'Invalid license key signature' };
  }

  // Decode and parse JSON payload
  let payload;
  try {
    payload = JSON.parse(Buffer.from(payloadB64, 'base64url').toString('utf8'));
  } catch {
    return { valid: false, error: 'Invalid license key payload' };
  }

  const { licensee, tier, seats, iat, exp } = payload;

  // Validate tier
  if (!VALID_TIERS.includes(tier)) {
    return { valid: false, error: 'Invalid license tier in key' };
  }

  // Check expiry
  if (exp != null && Number(exp) < Math.floor(Date.now() / 1000)) {
    return { valid: false, error: 'License key has expired' };
  }

  return {
    valid: true,
    licensee: String(licensee || 'Unknown'),
    tier: String(tier),
    seats: Number(seats) >= -1 ? Number(seats) : -1,
    issuedAt: iat != null ? Number(iat) : null,
    expiresAt: exp != null ? Number(exp) : null,
  };
}

/**
 * Load and validate a license from the LICENSE_KEY environment variable.
 * This is called **synchronously** at startup by edition.js.
 *
 * @returns {{ valid: boolean, licensee?: string, tier?: string, seats?: number,
 *             expiresAt?: number|null } | null}
 */
function loadLicenseFromEnv() {
  const key = process.env.LICENSE_KEY;
  if (!key) return null;
  return parseLicenseKey(key);
}

/**
 * Update the in-memory active license cache.
 * Called after the license is activated at runtime (via API) or loaded from DB
 * at startup.  Avoids mutating process.env at runtime.
 *
 * @param {{ raw: string } & ReturnType<typeof parseLicenseKey> | null} license
 */
function setActiveLicense(license) {
  _activeLicense = license;
}

/**
 * Return the currently active license.
 * Prefers the env-var source (set at process start), then falls back to the
 * in-memory cache populated by setActiveLicense().
 *
 * @returns {{ valid: boolean, licensee?: string, tier?: string, seats?: number,
 *             raw?: string } | null}
 */
function getActiveLicense() {
  const envLicense = loadLicenseFromEnv();
  if (envLicense && envLicense.valid) return envLicense;
  return _activeLicense;
}

/**
 * Clear the in-memory active license cache (used when license is removed).
 */
function clearActiveLicense() {
  _activeLicense = null;
}

/**
 * Load and validate a license stored in the database.
 * Called **asynchronously** after server startup as a fallback when
 * LICENSE_KEY is not set in the environment.
 *
 * @returns {Promise<{ valid: boolean, licensee?: string, tier?: string,
 *                     seats?: number, raw?: string } | null>}
 */
async function loadLicenseFromDb() {
  try {
    const pool = require('../config/database');
    const result = await pool.query(
      `SELECT config_value
       FROM dynamic_config_entries
       WHERE organization_id IS NULL
         AND config_domain = $1
         AND config_key = $2
         AND is_active = true
       LIMIT 1`,
      ['license', 'active_license']
    );
    if (result.rows.length === 0) return null;

    const stored = result.rows[0].config_value;
    const rawKey = stored && stored.key;
    if (!rawKey) return null;

    const parsed = parseLicenseKey(rawKey);
    return parsed.valid ? { ...parsed, raw: rawKey } : null;
  } catch {
    // Table may not exist yet (early startup / migrations not yet run)
    return null;
  }
}

/**
 * Persist a validated license key in the database so it survives restarts.
 *
 * @param {string} key       - The raw license key string
 * @param {string|null} [updatedBy] - User ID who activated the license
 * @returns {Promise<void>}
 */
async function storeLicenseInDb(key, updatedBy = null) {
  const pool = require('../config/database');
  const value = JSON.stringify({ key });

  // Update if exists, else insert (NULL org_id prevents UNIQUE constraint use)
  const updateResult = await pool.query(
    `UPDATE dynamic_config_entries
     SET config_value = $1::jsonb,
         is_active    = true,
         updated_by   = $2,
         updated_at   = NOW()
     WHERE organization_id IS NULL
       AND config_domain = 'license'
       AND config_key    = 'active_license'
     RETURNING id`,
    [value, updatedBy]
  );

  if (updateResult.rowCount === 0) {
    await pool.query(
      `INSERT INTO dynamic_config_entries
         (organization_id, config_domain, config_key, config_value, is_active, updated_by, updated_at)
       VALUES (NULL, 'license', 'active_license', $1::jsonb, true, $2, NOW())`,
      [value, updatedBy]
    );
  }
}

/**
 * Remove the active license key from the database.
 *
 * @returns {Promise<boolean>} true if a row was deleted
 */
async function removeLicenseFromDb() {
  const pool = require('../config/database');
  const result = await pool.query(
    `DELETE FROM dynamic_config_entries
     WHERE organization_id IS NULL
       AND config_domain = 'license'
       AND config_key    = 'active_license'`
  );
  return (result.rowCount || 0) > 0;
}

module.exports = {
  parseLicenseKey,
  loadLicenseFromEnv,
  loadLicenseFromDb,
  storeLicenseInDb,
  removeLicenseFromDb,
  getActiveLicense,
  setActiveLicense,
  clearActiveLicense,
};


/**
 * Returns the signing secret.  In production this must be set via the
 * LICENSE_SECRET environment variable; the fallback is intentionally weak so
 * that self-generated test keys never validate on a real deployment.
 */
function getSecret() {
  return process.env.LICENSE_SECRET || 'controlweave-ce-license-v1-dev';
}

/**
 * Compute the expected HMAC for the given base64url-encoded payload segment.
 *
 * @param {string} payloadB64 - The base64url-encoded payload string (no dots)
 * @returns {string} 64-character lower-case hex string
 */
function computeSignature(payloadB64) {
  return crypto
    .createHmac('sha256', getSecret())
    .update(`${LICENSE_VERSION}.${payloadB64}`)
    .digest('hex');
}

/**
 * Parse and validate a license key string.
 *
 * @param {string} key - The raw license key (e.g. "v1.eyJ....<hex>")
 * @returns {{ valid: boolean, licensee?: string, tier?: string, seats?: number,
 *             issuedAt?: number|null, expiresAt?: number|null, error?: string }}
 */
function parseLicenseKey(key) {
  if (!key || typeof key !== 'string') {
    return { valid: false, error: 'No license key provided' };
  }

  const parts = key.trim().split('.');
  if (parts.length !== 3 || parts[0] !== LICENSE_VERSION) {
    return { valid: false, error: 'Invalid license key format' };
  }

  const [, payloadB64, signature] = parts;

  // Validate hex signature length (SHA-256 → 64 hex chars)
  if (!/^[0-9a-f]{64}$/i.test(signature)) {
    return { valid: false, error: 'Invalid license key signature format' };
  }

  // Constant-time HMAC comparison
  const expected = computeSignature(payloadB64);
  try {
    if (!crypto.timingSafeEqual(
      Buffer.from(expected, 'hex'),
      Buffer.from(signature.toLowerCase(), 'hex')
    )) {
      return { valid: false, error: 'Invalid license key signature' };
    }
  } catch {
    return { valid: false, error: 'Invalid license key signature' };
  }

  // Decode and parse JSON payload
  let payload;
  try {
    payload = JSON.parse(Buffer.from(payloadB64, 'base64url').toString('utf8'));
  } catch {
    return { valid: false, error: 'Invalid license key payload' };
  }

  const { licensee, tier, seats, iat, exp } = payload;

  // Validate tier
  if (!VALID_TIERS.includes(tier)) {
    return { valid: false, error: 'Invalid license tier in key' };
  }

  // Check expiry
  if (exp != null && Number(exp) < Math.floor(Date.now() / 1000)) {
    return { valid: false, error: 'License key has expired' };
  }

  return {
    valid: true,
    licensee: String(licensee || 'Unknown'),
    tier: String(tier),
    seats: Number(seats) >= -1 ? Number(seats) : -1,
    issuedAt: iat != null ? Number(iat) : null,
    expiresAt: exp != null ? Number(exp) : null,
  };
}

/**
 * Load and validate a license from the LICENSE_KEY environment variable.
 * This is called **synchronously** at startup by edition.js.
 *
 * @returns {{ valid: boolean, licensee?: string, tier?: string, seats?: number,
 *             expiresAt?: number|null } | null}
 */
function loadLicenseFromEnv() {
  const key = process.env.LICENSE_KEY;
  if (!key) return null;
  return parseLicenseKey(key);
}

/**
 * Load and validate a license stored in the database.
 * Called **asynchronously** after server startup as a fallback when
 * LICENSE_KEY is not set in the environment.
 *
 * @returns {Promise<{ valid: boolean, licensee?: string, tier?: string,
 *                     seats?: number, key?: string } | null>}
 */
async function loadLicenseFromDb() {
  try {
    const pool = require('../config/database');
    const result = await pool.query(
      `SELECT config_value
       FROM dynamic_config_entries
       WHERE organization_id IS NULL
         AND config_domain = $1
         AND config_key = $2
         AND is_active = true
       LIMIT 1`,
      ['license', 'active_license']
    );
    if (result.rows.length === 0) return null;

    const stored = result.rows[0].config_value;
    const rawKey = stored && stored.key;
    if (!rawKey) return null;

    const parsed = parseLicenseKey(rawKey);
    return parsed.valid ? { ...parsed, key: rawKey } : null;
  } catch {
    // Table may not exist yet (early startup / migrations not yet run)
    return null;
  }
}

/**
 * Persist a validated license key in the database so it survives restarts.
 *
 * @param {string} key       - The raw license key string
 * @param {string|null} [updatedBy] - User ID who activated the license
 * @returns {Promise<void>}
 */
async function storeLicenseInDb(key, updatedBy = null) {
  const pool = require('../config/database');
  const value = JSON.stringify({ key });

  // Update if exists, else insert (NULL org_id prevents UNIQUE constraint use)
  const updateResult = await pool.query(
    `UPDATE dynamic_config_entries
     SET config_value = $1::jsonb,
         is_active    = true,
         updated_by   = $2,
         updated_at   = NOW()
     WHERE organization_id IS NULL
       AND config_domain = 'license'
       AND config_key    = 'active_license'
     RETURNING id`,
    [value, updatedBy]
  );

  if (updateResult.rowCount === 0) {
    await pool.query(
      `INSERT INTO dynamic_config_entries
         (organization_id, config_domain, config_key, config_value, is_active, updated_by, updated_at)
       VALUES (NULL, 'license', 'active_license', $1::jsonb, true, $2, NOW())`,
      [value, updatedBy]
    );
  }
}

/**
 * Remove the active license key from the database.
 *
 * @returns {Promise<boolean>} true if a row was deleted
 */
async function removeLicenseFromDb() {
  const pool = require('../config/database');
  const result = await pool.query(
    `DELETE FROM dynamic_config_entries
     WHERE organization_id IS NULL
       AND config_domain = 'license'
       AND config_key    = 'active_license'`
  );
  return (result.rowCount || 0) > 0;
}

module.exports = {
  parseLicenseKey,
  loadLicenseFromEnv,
  loadLicenseFromDb,
  storeLicenseInDb,
  removeLicenseFromDb,
  getActiveLicense,
  setActiveLicense,
  clearActiveLicense,
};
